In [ ]:
class Batsman():  #vvi

    def __init__(self,*args):
        self.name = "New Batsman"

        if len(args)==2:
            self.run=args[0]
            self.balls_faced=args[1]
        if len(args)==3:
            self.run=args[1]
            self.balls_faced=args[2]
            self.name=args[0]

    def printcareerstatistics(self):
        print("Name:",self.name)
        print(f"Run Scored : {self.run}, and balls faced : {self.balls_faced}")

    def batting_strke_rate(self):

        strike_rate=(self.run/self.balls_faced)*100

        return strike_rate

# Write your code here
b1 = Batsman(6101, 7380)
b1.printcareerstatistics()
b1.batting_strke_rate()
print(b1.batting_strke_rate())
print("=================")

b2 = Batsman("Liton",2350,2100)
b2.printcareerstatistics()
b2.batting_strke_rate()
print(b2.batting_strke_rate())

Name: New Batsman
Run Scored : 6101, and balls faced : 7380
82.66937669376694
=================
Name: Liton
Run Scored : 2350, and balls faced : 2100
111.90476190476191

In [ ]:
print(-1%3)
print(-1/3)

2
-0.3333333333333333

In [ ]:
class Account :
    def __init__(self, *args):

        self.name= "Default Account"
        self.balance = 0.0

        if len(args)==1:
            self.name=args[0]
        if len(args)==2:
            self.name=args[0]
            self.balance=args[1]
    def details(self):

         return f"{self.name}\n{self.balance:.1f}"


    def withdraw(self,taka):
        if self.balance > taka:
            print( "Withdrawn ")
        else:
            print("Not succesful")

a1 = Account()
a1.details()
print(a1.details())
a1.name="liam"
a1.balance=1000000000
a1.details()
print(a1.details())
a1.withdraw(1000000000)
a1.withdraw(500000)

Default Account
0.0
liam
1000000000.0
Not succesful
Withdrawn

In [ ]:
class Joker:
  def __init__(self, name, power, is_he_psycho):
    self.name = name
    self.power = power
    self.is_he_psycho = is_he_psycho
  def print_details(self):
    print("Name:", self.name)
    print("Power:", self.power)
    if self.is_he_psycho== True:
      print("Is he psycho? Yes")
    else:
      print("Is he psycho? No")
  def change_name(self, new_name):
    print("Changing name of joker")
    self.name = new_name
j1 = Joker('Heath Ledger', 'Mind Game', False)
print(j1.name)
print(j1.power)
print(j1.is_he_psycho)
print("===================")
j1.print_details()
print("===================")
j1.change_name('Joaquin Phoenix')
print("===================")
j1.print_details()

Heath Ledger
Mind Game
False
===================
Name: Heath Ledger
Power: Mind Game
Is he psycho? No
===================
Changing name of joker
===================
Name: Joaquin Phoenix
Power: Mind Game
Is he psycho? No

In [ ]:
class Student:
    def __init__ (self,name=None):
        if name == None:
            self.name = "Default Student"

        else:
            self.name = name
    def quizcalc(self,*ab):
        self.avg_score=0

        if len (ab) == 1:
            self.avg_score = ab[0]/3
        if len (ab) == 2:
            self.avg_score = ab[0] + ab[1] / 3
        if len (ab) == 3 :
            self.avg_score = ab[0] + ab[1] + ab[2] /3

    def printdetails(self):
        print("Hello ", self.name)
        print ("Your average score is ", self.avg_score,2)



s1 = Student()
s1.quizcalc(10)
print("----------------------")
s1.printdetails()
s2 = Student("Harry")
s2.quizcalc(10,8)
print("----------------------")
s2.printdetails()
s3 = Student("Hermoine")
s3.quizcalc(10,9,10)
print("----------------------")
s3.printdetails()

----------------------
Hello  Default Student
Your average score is  3.3333333333333335 2
----------------------
Hello  Harry
Your average score is  12.666666666666666 2
----------------------
Hello  Hermoine
Your average score is  22.333333333333332 2

In [ ]:
class Farmer :

    def __init__(self, name_or_id=None):
        self.crops=[]
        self.fish=[]
        self.name_or_id = name_or_id
        if type(self.name_or_id)== str:
            print("Hello",self.name_or_id,"Welcome to your farm")
        elif type(self.name_or_id)== int :
            print("Welcome to your farm your farm id is",str(self.name_or_id)+"!")
        elif self.name_or_id == None:
            print("Welcome to your farm")

    def addCrops(self,*crops):
        if len(crops)==0:
            print("No crops are added")
        else:
            self.crops+=crops
            print(len(crops),"crops are added")
    def addFishes(self,*Fish):
             if len(Fish)==0:
                print("No fishes are added")
             else:
                 self.fish+=Fish
                 print(len(Fish),"fishes are added")
    def showGoods(self):
        if len(self.crops)>=1:
            print("You have",len(self.crops),"crops")
            for i in range(len(self.crops)):
                if (i==len(self.crops)-1):
                    print(self.crops[i],end=' ')
                    print()
                else:
                    print(self.crops[i],end=',')

        else:
            print("You don't have any crops")

        if len(self.fish)>=1:
            print("You have",len(self.fish),"Fishes")
            for i in range(len(self.fish)):
                if (i==len(self.fish)-1):
                    print(self.fish[i],end=' ')
                    print()
                else:
                    print(self.fish[i],end=',')
        else:
            print("You don't have any fishes")

f1 = Farmer()
print("-------------------")
f1.addCrops('Rice', "Jute", "Cinnamon")
print("-------------------")
f1.addFishes()
print("-------------------")
f1.addCrops('Mustard')
print("-------------------")
f1.showGoods()
print("-------------------")
f2 = Farmer("Korim Mia")
print("-------------------")
f2.addFishes('Pangash', 'Magur')
print("-------------------")
f2.addCrops("Wheat", "Potato")
print("-------------------")
f2.addFishes("Koi", "Tuna", "Sardine")
print("-------------------")
f2.showGoods()
print("-------------------")
f3 = Farmer(2865127000)
print("-------------------")
f3.addCrops()
print("-------------------")
f3.addFishes("Katla")
print("-------------------")
f3.showGoods()
print("-------------------")

Welcome to your farm
-------------------
3 crops are added
-------------------
No fishes are added
-------------------
1 crops are added
-------------------
You have 4 crops
Rice,Jute,Cinnamon,Mustard
You don't have any fishes
-------------------
Hello Korim Mia Welcome to your farm
-------------------
2 fishes are added
-------------------
2 crops are added
-------------------
3 fishes are added
-------------------
You have 2 crops
Wheat,Potato
You have 5 Fishes
Pangash,Magur,Koi,Tuna,Sardine
-------------------
Welcome to your farm your farm id is 2865127000!
-------------------
No crops are added
-------------------
1 fishes are added
-------------------
You don't have any crops
You have 1 Fishes
Katla
-------------------

Very Very Important

In [ ]:
class Author() :

    def __init__(self,Author=None):
        self.Author = Author
        self.dict1={}

    def setName(self,Author):
        self.Author = Author

    def addBook(self,name,types):
        if self.Author == None :
            print("A book can not be added without author name")

        else:
            if types not in self.dict1:
                self.dict1[types]=[name]
            else:
                self.dict1[types].append(name)

    def printDetail(self):
        print("Author Name:",self.Author)
        for types,name in self.dict1.items():
            print(types,":" , "," .join(name))

a1 = Author()
print("===============================")
a1.addBook("Ice", "Science Fiction")
print("===============================")
a1.setName("Anna Kavan")
a1.addBook("Ice", "Science Fiction")
a1.printDetail()
print("===============================")
a2 = Author("Humayun Ahmed")
a2.addBook("Onnobhubon","Science Fiction")
a2.addBook("Megher Upor Bari", "Horror")
print("===============================")
a2.printDetail()
a2.addBook("Ireena", "Science Fiction")
print("===============================")
a2.printDetail()
print("===============================")

===============================
A book can not be added without author name
===============================
Author Name: Anna Kavan
Science Fiction : Ice
===============================
===============================
Author Name: Humayun Ahmed
Science Fiction : Onnobhubon
Horror : Megher Upor Bari
===============================
Author Name: Humayun Ahmed
Science Fiction : Onnobhubon,Ireena
Horror : Megher Upor Bari
===============================

better way

In [ ]:
class Author() :

    def __init__(self,Author=None):
        self.Author = Author
        self.l=[]

    def setName(self,Author):
        self.Author = Author

    def addBook(self,name,types):
        if self.Author == None :
            print("A book can not be added without author name")

        else:
            self.l.append((types,name))

    def printDetail(self):
        print("Author Name:",self.Author)
        for types,name in self.l:
            print(types,":",name)

a1 = Author()
print("===============================")
a1.addBook("Ice", "Science Fiction")
print("===============================")
a1.setName("Anna Kavan")
a1.addBook("Ice", "Science Fiction")
a1.printDetail()
print("===============================")
a2 = Author("Humayun Ahmed")
a2.addBook("Onnobhubon","Science Fiction")
a2.addBook("Megher Upor Bari", "Horror")
print("===============================")
a2.printDetail()
a2.addBook("Ireena", "Science Fiction")
print("===============================")
a2.printDetail()
print("===============================")

===============================
A book can not be added without author name
===============================
Author Name: Anna Kavan
Science Fiction : Ice
===============================
===============================
Author Name: Humayun Ahmed
Science Fiction : Onnobhubon
Horror : Megher Upor Bari
===============================
Author Name: Humayun Ahmed
Science Fiction : Onnobhubon
Horror : Megher Upor Bari
Science Fiction : Ireena
===============================

very very important

In [ ]:
class CoffeeMachine:

    def __init__(self,Brand_name):
        self.Brand_name= Brand_name
        self.ingd=[]

    def insertIngridients(self,*a):
        self.ingd+=a
    def getDetails(self):
        details = "Brand Name: " + self.Brand_name + "\nIngredients: " + ", ".join(self.ingd)
        return details
cm1 =CoffeeMachine('Miyako')
cm1.insertIngridients('Coffee Beans', 'Milk', 'Sugar')
print(cm1.getDetails())

Brand Name: Miyako
Ingredients: Coffee Beans, Milk, Sugar

In [ ]:
import math
class Sphere:
    def __init__(self,radious):
        self.radious=radious

    def get_radius(self):
        return self.radious
    def get_volume(self):
        volume = (4/3) * math.pi * (self.radious ** 3)
        return volume
    def get_surface_area(self):
        surface_area = 4 * math.pi * (self.radious ** 2)
        return surface_area
s = Sphere(5.0)
print("Radius of the sphere:", s.get_radius())
print("Volume of the sphere:", s.get_volume())
print("Surface area of the sphere:", s.get_surface_area())

Radius of the sphere: 5.0
Volume of the sphere: 523.5987755982989
Surface area of the sphere: 314.1592653589793

In [ ]:
class Country:

    def __init__(self):
        self.name="Bangladesh"
        self.continent = "Asia"
        self.capital="Dhaka"
        self.fifa_ranking= 187

country = Country()
print('Name:',country.name)
print('Continent:',country.continent)
print('Capital:',country.capital)
print('Fifa Ranking:',country.fifa_ranking)
print('===================')
country.name = "Belgium"
country.continent = "Europe"
country.capital = "Brussels"
country.fifa_ranking = 1
print('Name:',country.name)
print('Continent:',country.continent)
print('Capital:',country.capital)
print('Fifa Ranking:',country.fifa_ranking)

Name: Bangladesh
Continent: Asia
Capital: Dhaka
Fifa Ranking: 187
===================
Name: Belgium
Continent: Europe
Capital: Brussels
Fifa Ranking: 1

In [ ]:
class Customer:
    def __init__(self,name):
        self.name = name
        self.l=[]
    def greet(self,name=None):
        if name==None:
            print("hello!")
        else:
            print("hello!",name)

    def purchase(self,*a):
        self.l+=a
        print(self.name,"you purchase",len(self.l),"items")

        print(",".join(self.l))

customer_1 = Customer("Sam")
customer_1.greet()
customer_1.purchase("chips", "chocolate", "orange juice")
print("-----------------------------")
customer_2 = Customer("David")
customer_2.greet("David")
customer_2.purchase("orange juice")

hello!
Sam you purchase 3 items
chips,chocolate,orange juice
-----------------------------
hello! David
David you purchase 1 items
orange juice

In [ ]:
class Patient:
    def __init__(self,name,age):
        self.name = name
        self.age = age
        self.l=[]
    def add_Symptom(self,*a):
        self.l+=a
    def printPatientDetail(self):
        print("Name:",self.name)
        print("Age",self.age)
        print("Symptomps:",','.join(self.l))


p1 = Patient('Thomas', 23)
p1.add_Symptom('Headache')
p2 = Patient('Carol', 20)
p2.add_Symptom('Vomiting', 'Coughing')
p3 = Patient('Mike', 25)
p3.add_Symptom('Fever', 'Headache', 'Coughing')
print("=========================")
p1.printPatientDetail()
print("=========================")
p2.printPatientDetail()
print("=========================")
p3.printPatientDetail()

=========================
Name: Thomas
Age 23
Symptomps: Headache
=========================
Name: Carol
Age 20
Symptomps: Vomiting,Coughing
=========================
Name: Mike
Age 25
Symptomps: Fever,Headache,Coughing

In [ ]:
class Queue:

    def __init__(self):
        self.l= []

    def enqueue(self, item):
        self.l.append(item)

    def dequeue(self):
        if len(self.l)>0:
            return self.l.pop(0)
    def is_empty(self) :
        if len(self.l)==0:
            return True
        else:
            return False
    def size(self):
        return len(self.l)

    def size(self):

        return len(self.l)

q = Queue()
print("Is the queue empty?", q.is_empty())  # True

q.enqueue(1)
q.enqueue(2)
q.enqueue(3)

print("Queue size:", q.size())  # 3
print("Dequeue:", q.dequeue())   # 1
print("Queue size after dequeue:", q.size())  # 2
print("Is the queue empty?", q.is_empty())  # False

Is the queue empty? True
Queue size: 3
Dequeue: 1
Queue size after dequeue: 2
Is the queue empty? False

In [ ]:

class Scope:

    def __init__(self):

        self.x, self.y = 1, 100

    def met1(self):

        x = 3

        x = self.x + 1

        self.y = self.y + self.x + 1

        x = self.y + self.met2() + self.y

        print(x, self.y)

    def met2(self):

        y = 0

        print(self.x, y)

        self.x = self.x + y

        self.y = self.y + 200

        return self.x + y

q2 = Scope()
q2.met1()
q2.met2()
q2.met1()
q2.met2()

1 0
405 302
1 0
1 0
1209 704
1 0

1

In [ ]:
class Author:
    def __init__(self,Author=None):
        self.Author = Author
        self.l={}

    def setName(self,Author):
        self.Author=Author

    def addBook(self,name,types):
        if self.Author == None:
            print("A book cannot be addeed without a Author name")
        else:
            if types not in self.l:
                self.l[types]=[name]
            else:
                self.l[types].append(name)

    def printDetail(self):
        print("Author Name:",self.Author)
        for types,name in self.l.items():
            print(types,":","," .join(name))

a1 = Author()
print("===============================")
a1.addBook("Ice", "Science Fiction")
print("===============================")
a1.setName("Anna Kavan")
a1.addBook("Ice", "Science Fiction")
a1.printDetail()
print("===============================")
a2 = Author("Humayun Ahmed")
a2.addBook("Onnobhubon","Science Fiction")
a2.addBook("Megher Upor Bari", "Horror")
print("===============================")
a2.printDetail()
a2.addBook("Ireena", "Science Fiction")
print("===============================")
a2.printDetail()
print("===============================")

===============================
A book cannot be addeed without a Author name
===============================
Author Name: Anna Kavan
Science Fiction : Ice
===============================
===============================
Author Name: Humayun Ahmed
Science Fiction : Onnobhubon
Horror : Megher Upor Bari
===============================
Author Name: Humayun Ahmed
Science Fiction : Onnobhubon,Ireena
Horror : Megher Upor Bari
===============================

Composition(Take a relationship)

In [ ]:
class Engine:
    def __init__(self,cc):
        self.cc=cc

    def start(self):
        print("Engine Started")
    def stop(self):
        print("Engine Stopped")

class Car:
    def __init__(self,name,cc):
        self.name=name
        self.engine=Engine(cc)

    def run(self):
        print("car runs")
        self.engine.start()


c1 = Car("BMW",20000)
c1.run()

car runs
Engine Started

Aggregation(Has a relationship)

In [ ]:
class Engine:
    def __init__(self,cc):
        self.cc=cc

    def start(self):
        print("Engine Started")
    def stop(self):
        print("Engine Stopped")

class Car:
    def __init__(self,name,engi):
        self.name=name
        self.engine=engi

    def run(self):
        print("car runs")
        self.engine.start()

e1=Engine(20000)
c1=Car("BMW",e1)
c1.run()

car runs
Engine Started

In [ ]:
class Spaceship:

    def __init__(self,name,capacity):
        self.name=name
        self.capacity=capacity
        self.l=[]
        self.sum=0

    def load_cargo(self,material):
        if self.sum + material.get_weight() <= self.capacity :
            self.sum+=material.get_weight()
            self.l.append(material.get_name())
        else:
            exceed_weight = (self.sum + material.get_weight()) - self.capacity
            print("Unable to load",material.get_name(),"inside",self.name,".","Exceeds Capacity by",exceed_weight)

    def display_details(self):
        print("Spaceship Name :",self.name)
        print("Sapceship Capacity :",self.capacity)
        print("Current Cargo Weight:",self.sum)
        print("Cargo:", self.l)


class Cargo:

    def __init__(self,name,weight):
        self._name=name
        self._weight=weight
    def get_name(self):
        return self._name
    def get_weight(self):
        return self._weight
# Driver Code
falcon = Spaceship("Falcon", 50000)
apollo = Spaceship("Apollo", 100000)
enterprise = Spaceship("Enterprise", 220000)
print("1.===================================")

gold = Cargo("Gold", 20000)
platinum = Cargo("Platinum", 25000)
dilithium = Cargo("Dilithium", 50000)
trilithium = Cargo("Trilithium", 70000)
neutronium = Cargo("Neutronium", 80000)
print("2.===================================")

falcon.load_cargo(gold)
falcon.load_cargo(platinum)
falcon.display_details()
print("3.===================================")

apollo.load_cargo(gold)
apollo.display_details()
print("4.===================================")

falcon.load_cargo(neutronium)
print("5.===================================")

enterprise.load_cargo(dilithium)
enterprise.load_cargo(trilithium)
enterprise.load_cargo(neutronium)
enterprise.display_details()

1.===================================
2.===================================
Spaceship Name : Falcon
Sapceship Capacity : 50000
Current Cargo Weight: 45000
Cargo: ['Gold', 'Platinum']
3.===================================
Spaceship Name : Apollo
Sapceship Capacity : 100000
Current Cargo Weight: 20000
Cargo: ['Gold']
4.===================================
Unable to load Neutronium inside Falcon . Exceeds Capacity by 75000
5.===================================
Spaceship Name : Enterprise
Sapceship Capacity : 220000
Current Cargo Weight: 200000
Cargo: ['Dilithium', 'Trilithium', 'Neutronium']

In [ ]:
class RickMote:

    def __init__(self):
        self.channel_index = 0
        self.volume=3
        self.l=[0,2,3,6,7,9]
        self.p=False

    def power(self):
        if self.p==False:
            self.p=True
        else:
            self.p=False

    def changeChannel(self,n=None):
        if self.p==True:
            if n==None:
                if self.channel_index==5:
                    print("Cannot go beyond channel 9")
                else:
                    self.channel_index+=1
            elif n in self.l:
                self.channel_index=self.l.index(n)

            else:
                print("TV channel does not exist")
        else:
            print("Power is turned off. Cannot change channel.")

    def changeVolumeLevel(self, l=None):
        if self.p==True:
            if l==None:
                self.volume+=1
            else:
                self.volume+=l
        else:
            print("Power is turned off. Cannot change volume.")

    def showInfo(self):
      print("ID cable box status")
      if self.p:
        print("Cable box is:ON")
        print("Channel", self.l[self.channel_index])
        print("Volume", self.volume)
      else:
        print("Cable box is:OFF")

oTV = RickMote()
oTV.power()
print("1.############################")
oTV.showInfo()
print("2.############################")
oTV.changeChannel()
oTV.changeVolumeLevel()
oTV.showInfo()
print("3.############################")
oTV.power()
oTV.showInfo()
print("4.############################")
oTV.power()
oTV.changeVolumeLevel(4)
oTV.changeChannel(3)
oTV.showInfo()
print("5.############################")
oTV.changeVolumeLevel(-2)
oTV.showInfo()
print("6.############################")
oTV.power()
oTV.changeChannel(9)
oTV.changeVolumeLevel(-1)
oTV.showInfo()
print("7.############################")
oTV.power()
oTV.changeChannel(11)
oTV.showInfo()

1.############################
ID cable box status
Cable box is:ON
Channel 0
Volume 3
2.############################
ID cable box status
Cable box is:ON
Channel 2
Volume 4
3.############################
ID cable box status
Cable box is:OFF
4.############################
ID cable box status
Cable box is:ON
Channel 3
Volume 8
5.############################
ID cable box status
Cable box is:ON
Channel 3
Volume 6
6.############################
Power is turned off. Cannot change channel.
Power is turned off. Cannot change volume.
ID cable box status
Cable box is:OFF
7.############################
TV channel does not exist
ID cable box status
Cable box is:ON
Channel 3
Volume 6

VVi

In [ ]:
class  Spaceship:

    def __init__(self,name,capacity):
        self.name=name
        self.capacity=capacity
        self.cargos=[]
        self.sum=0

    def load_cargo(self,cargo):
        if self.sum+cargo.get_weight() <= self.capacity:
            self.cargos.append(cargo.get_material())
            self.sum+=cargo.get_weight()
        else:
            print("Warning unable to put",cargo.get_material())
            print(f"Exceed Capacity by {self.sum+cargo.get_weight()-self.capacity} ")

    def display_details(self):
        print("Spaceship Name:", self.name)
        print("Capacity:", self.capacity)
        print("Current Cargo Weight:", self.sum)
        # for i in self.cargo:
        #   print(i.get_name())
        print("Cargo:", self.cargos)

class Cargo:
    def __init__(self,material,weight):
        self._material=material
        self._weight=weight

    def get_weight(self):
        return self._weight

    def get_material(self):
        return self._material

# Driver Code
falcon = Spaceship("Falcon", 50000)
apollo = Spaceship("Apollo", 100000)
enterprise = Spaceship("Enterprise", 220000)
print("1.===================================")

gold = Cargo("Gold", 20000)
platinum = Cargo("Platinum", 25000)
dilithium = Cargo("Dilithium", 50000)
trilithium = Cargo("Trilithium", 70000)
neutronium = Cargo("Neutronium", 80000)
print("2.===================================")

falcon.load_cargo(gold)
falcon.load_cargo(platinum)
falcon.display_details()
print("3.===================================")

apollo.load_cargo(gold)
apollo.display_details()
print("4.===================================")

falcon.load_cargo(neutronium)
print("5.===================================")

enterprise.load_cargo(dilithium)
enterprise.load_cargo(trilithium)
enterprise.load_cargo(neutronium)
enterprise.display_details()

1.===================================
2.===================================
Spaceship Name: Falcon
Capacity: 50000
Current Cargo Weight: 45000
Cargo: ['Gold', 'Platinum']
3.===================================
Spaceship Name: Apollo
Capacity: 100000
Current Cargo Weight: 20000
Cargo: ['Gold']
4.===================================
Warning unable to put Neutronium
Exceed Capacity by 75000
5.===================================
Spaceship Name: Enterprise
Capacity: 220000
Current Cargo Weight: 200000
Cargo: ['Dilithium', 'Trilithium', 'Neutronium']

VVi

In [ ]:
class Student:

    def __init__(self,name,id,cg):
        self.name=name
        self.id=id
        self.cg=cg

    def setId(self,new_id):
        self.id = new_id

class Department:

    def __init__(self,dep):
        self.dep=dep
        self.l=[]

    def addStudent(self,*s):
        for  student in s:
            for info in self.l:
                if student.id == info.id :
                    print("Student with the same id already exists please try another id")
                    break
            else:
                self.l.append(student)
                print(f"Welcome to {self.dep} department {student.name}")

    def findStudent(self, student_id):
        for i in self.l:
            if i.id==student_id:
                print("Student info:")
                print("Student Name:", i.name)
                print("ID:", i.id)
                print("CGPA: ", i.cg)
                break
        else:
            print("Student with this ID doesn't exist, Please give a valid ID")

    def details(self):
        print("Department Name:", self.dep)
        print("Number of student:", len(self.l))
        print("Details of the students: ")
        for student in self.l:
            print("Student name:", student.name + ",", "ID:", str(student.id) + ",", "cgpa:", str(student.cg))

s1 = Student("Akib", 22301010, 3.29)
s2 = Student("Reza", 22101010, 3.45)
s3 = Student("Ruhan", 23101934, 4.00)
print("1==================================")
cse = Department("CSE")
cse.findStudent(22112233)
print("2==================================")
cse.addStudent(s1, s2, s3)
print("3==================================")
cse.details()
print("4==================================")
cse.findStudent(22301010)
print("5==================================")
s4 = Student("Nakib", 22301010, 3.22)
cse.addStudent(s4)
print("6==================================")
s4.setId(21201220)
cse.addStudent(s4)
print("7==================================")
cse.details()
print("8==================================")
s5 = Student("Sakib", 22201010, 2.29)
cse.addStudent(s5)
print("9==================================")
cse.details()

1==================================
Student with this ID doesn't exist, Please give a valid ID
2==================================
Welcome to CSE department Akib
Welcome to CSE department Reza
Welcome to CSE department Ruhan
3==================================
Department Name: CSE
Number of student: 3
Details of the students:
Student name: Akib, ID: 22301010, cgpa: 3.29
Student name: Reza, ID: 22101010, cgpa: 3.45
Student name: Ruhan, ID: 23101934, cgpa: 4.0
4==================================
Student info:
Student Name: Akib
ID: 22301010
CGPA:  3.29
5==================================
Student with the same id already exists please try another id
6==================================
Welcome to CSE department Nakib
7==================================
Department Name: CSE
Number of student: 4
Details of the students:
Student name: Akib, ID: 22301010, cgpa: 3.29
Student name: Reza, ID: 22101010, cgpa: 3.45
Student name: Ruhan, ID: 23101934, cgpa: 4.0
Student name: Nakib, ID: 21201220, cgpa: 3.22
8==================================
Welcome to CSE department Sakib
9==================================
Department Name: CSE
Number of student: 5
Details of the students:
Student name: Akib, ID: 22301010, cgpa: 3.29
Student name: Reza, ID: 22101010, cgpa: 3.45
Student name: Ruhan, ID: 23101934, cgpa: 4.0
Student name: Nakib, ID: 21201220, cgpa: 3.22
Student name: Sakib, ID: 22201010, cgpa: 2.29

In [ ]:
class Lab4:
    def __init__(self):
        self.x = 3
        self.y = 2
        self.sum = 5
    def methodA(self, x):
        self.y = self.sum + self.x - x
        self.sum = x - self.y
        d = Lab4()
        d.sum = self.sum + self.methodB(d)
        print(self.x, self.y, self.sum)
        return d
    def methodB(self, t, z = 4):
        y = 2
        t.x = self.x + self.sum
        y = y + t.x - t.y
        self.sum = t.x + t.y + y - z
        if z == 4:
            return y
        print(t.x, t.y, self.sum)
        p = t.methodA(y)
        print(t.x, self.y, p.sum)

obj = Lab4()
obj2 = obj.methodA(4)
obj.methodB(obj2, 10)

3 4 4
7 2 6
7 3 20
7 4 15

In [ ]:
class PC:
    def __init__(self,model,price,*extra):
        self.model=model
        self.price=price
        self.extra=[]
        for i in extra:
            self.extra.append(i)
    def specPC(self):
        x= ', '.join(self.extra)

        return f"Model Name: {self.model}\nPrice: {self.price}\nExtra Features: {x}"

    def addExtraParts(self,part,prices):
        self.extra.append(part)
        self.price+=prices

lenovo = PC('Lenovo IdeaPad', 80500,
'Backlit Keyboard', 'Touch', 'Type-C')
print(lenovo.specPC())
print('-------1--------')
lenovo.addExtraParts('CPU Cooler', 7000)
print(lenovo.specPC())

Model Name: Lenovo IdeaPad
Price: 80500
Extra Features: Backlit Keyboard, Touch, Type-C
-------1--------
Model Name: Lenovo IdeaPad
Price: 87500
Extra Features: Backlit Keyboard, Touch, Type-C, CPU Cooler

In [ ]:
class bKashAccount:

    def __init__(self,num,name,amount=0):
        self.num=num
        self.name=name
        self.amount=amount

    def addMoney(self,tk1):
        self.amount+=tk1
        print(f'Succeccsully added {tk1} to your account')

    def sendMoney(self,reciver,tk2):
        if self.amount>=tk2:
            reciver.amount+=tk2
            self.amount-=tk2
            print(f'Successfully Transfared Money')
        else:
            print('Money transfar is unsuccessful due to insufficient balance')

    def payBill(self,name,*location):
        for i in location:
            name1,money=i.split('_')
            money=int(money)
            if name1 in billers:
                if self.amount>=money:
                    print(f'Your {name1} bill payment is successfull')
                    self.amount-=money
                else:
                    print(f'{name1} bill payment is unsuccessful due to less amount of money')
            else:
                print(f'Sorry you cant pay {name1} bill through bkash payment')

    def details(self):
        return f'ACC No : {self.num}, Name: {self.name}, Balance:{self.amount } tk '



billers = ['Desco', 'Titas', 'Dhaka WASA',
'BTCL']
acc1 = bKashAccount('019278', 'Zafar')
acc2 = bKashAccount('018903', 'Abid', 300)
print(acc1.details())
print('-----------1---------')
acc1.addMoney(3000)
print('-----------2---------')
acc2.sendMoney(acc1, 500)
print('-----------3---------')
acc1.payBill(billers, 'Titas_2000',
'Desco_1200')
print('-----------4---------')
acc3 = bKashAccount('017262', 'Mostakim',
500)
print(acc2.details())
print(acc3.details())
print('-----------5---------')
acc1.sendMoney(acc3, 150)
print('-----------6---------')
acc2.payBill(billers, 'BTCL_750')
acc3.payBill(billers, 'Dot Internet_1500')
print('-----------7---------')
acc2.addMoney(5000)
acc3.addMoney(250)
print('-----------8---------')
acc2.payBill(billers, 'BTCL_750')
print('-----------9---------')
print(acc2.details())
print('-----------10---------')
print(acc3.details())

ACC No : 019278, Name: Zafar, Balance:0 tk
-----------1---------
Succeccsully added 3000 to your account
-----------2---------
Money transfar is unsuccessful due to insufficient balance
-----------3---------
Your Titas bill payment is successfull
Desco bill payment is unsuccessful due to less amount of money
-----------4---------
ACC No : 018903, Name: Abid, Balance:300 tk
ACC No : 017262, Name: Mostakim, Balance:500 tk
-----------5---------
Successfully Transfared Money
-----------6---------
BTCL bill payment is unsuccessful due to less amount of money
Sorry you cant pay Dot Internet bill through bkash payment
-----------7---------
Succeccsully added 5000 to your account
Succeccsully added 250 to your account
-----------8---------
Your BTCL bill payment is successfull
-----------9---------
ACC No : 018903, Name: Abid, Balance:4550 tk
-----------10---------
ACC No : 017262, Name: Mostakim, Balance:900 tk

In [ ]:
class MidA:
 def __init__(self, x, y=0):
    self.z = x+y
 def mA(self, z=5):
    temp= z + self.z
    if temp<8:
        self.z = self.z+ self.mB(temp)
    else:
        self.z = self.mB([temp,self.z])+ self.z
    print(z, temp, self.z)
 def mB(self, temp):
    self.z += self.z
    if type(temp)== int:
        return self.z + 5 + temp
    else:
        print(temp[0], temp[1], self.z)
        return self.z - 3 + temp[1]
m1= MidA(2, 3)
m1.mA(4)
m1= MidA(1)
m1.mA()

9 5 10
4 9 22
5 6 14

In [ ]:
class Student:
    def __init__(self,Name,cg,courses):
        self.name=Name
        self.cgpa=cg
        self.courses_taken=courses
        self.advising_status=None
        self.student_status=None
        if self.cgpa<2:
            if 1<=self.courses_taken<=2:
                self.student_status='Probation'
                print(f'Study hard this time {self.name}')
                self.advising_status='Approved'
            else:
                print(f'Sorry, {self.name}, you are on probation and cannot take more than 2 courses.')
                self.advising_status='Denied'
                self.courses_taken=0
                self.student_status='Probation'

        elif self.cgpa>=2:
            if 3<=self.courses_taken<=5:
                print(f'All the best, {self.name}, for the upcoming semester.')
                self.advising_status='Approved'
                self.student_status='Regular'
            else:
                self.advising_status='Denied'
                print(f'Hello {self.name}, You are a regular student and have to take between 3 to 5 courses.')
                self.courses_taken=0
                self.student_status='Regular'


s1 = Student("Clark", 3.45, 4)
print(f"Name: {s1.name}\nCGPA: {s1.cgpa}\nCourses Taken: {s1.courses_taken}")
print(f"Student Status: {s1.student_status}\nAdvising Status: {s1.advising_status}")
print("--------------------------------------------------------------------------------")
s2 = Student("Barry", 1.93, 2)
print(f"Name: {s2.name}")
print(f"Student Status: {s2.student_status}\nAdvising Status: {s2.advising_status}")
print("--------------------------------------------------------------------------------")
s3 = Student("Diana", 2.91, 2)
print(f"Advising Status: {s3.advising_status}\nCourses Taken: {s3.courses_taken}")
print("--------------------------------------------------------------------------------")
s4 = Student("Bruce", 1.52, 5)
print(f"Advising Status: {s4.advising_status}\nCourses Taken: {s4.courses_taken}")

All the best, Clark, for the upcoming semester.
Name: Clark
CGPA: 3.45
Courses Taken: 4
Student Status: Regular
Advising Status: Approved
--------------------------------------------------------------------------------
Study hard this time Barry
Name: Barry
Student Status: Probation
Advising Status: Approved
--------------------------------------------------------------------------------
Hello Diana, You are a regular student and have to take between 3 to 5 courses.
Advising Status: Denied
Courses Taken: 0
--------------------------------------------------------------------------------
Sorry, Bruce, you are on probation and cannot take more than 2 courses.
Advising Status: Denied
Courses Taken: 0

In [ ]:
#Task 1
class Customer:

    def __init__(self):
        self.price=0
        self.count=0
        self.sum=0
        print("Welcome to ABC Memorial Park ")

    def buyTicket(self,name,age):
        if self.count+1<=3:
            if age>10:
                self.price=100
                self.sum+=self.price
                print("Successfully purchased a ticket for",name+"!")
            elif age>0 and age<=10:
                self.price=50
                self.sum+=self.price
                print("Successfully purchased a ticket for",name+"!")
            self.count+=1
        else:
            print("You can't buy more than 3 tickets")

    def showDetails(self):
        print("Amount of tickets:",self.count)
        print("Total Price",self.sum)

print('1-------------------------')
customer1 = Customer()
print('2-------------------------')
customer1.buyTicket('Bob', 23)
customer1.buyTicket('Henry', 7)
customer1.buyTicket('Alexa', 30)
customer1.buyTicket('Jonas', 43)
print('3-------------------------')
customer1.showDetails()
print('4-------------------------')
customer2 = Customer()
print('5-------------------------')
customer2.buyTicket('Harry', 60)
customer2.buyTicket('Tomas', 28)
print('6-------------------------')
customer2.showDetails()

1-------------------------
Welcome to ABC Memorial Park
2-------------------------
Successfully purchased a ticket for Bob!
Successfully purchased a ticket for Henry!
Successfully purchased a ticket for Alexa!
You can't buy more than 3 tickets
3-------------------------
Amount of tickets: 3
Total Price 250
4-------------------------
Welcome to ABC Memorial Park
5-------------------------
Successfully purchased a ticket for Harry!
Successfully purchased a ticket for Tomas!
6-------------------------
Amount of tickets: 2
Total Price 200

In [ ]:
class GreenPhone:

    def __init__(self,model,version,camera):
        self.phone_company="Green Phone"
        self.model=model
        self.version=version
        self.camera=camera
        self.count=0
        self.a=1
        self.m=2
        self.u=3

    def updatePhone(self):
        if self.model[0]=='A':
            if self.count<self.a:
                self.version+=1
                self.count+=1
                print(f'Your phone Greenphone {self.model} is upgraded to Android Version:{self.version}')
            else:
                print(f'Your phone Greenphone {self.model} is already up to date')

        elif self.model[0]=='M' :
            if self.count<self.m:
                self.version+=1
                self.count+=1
                print(f'Your phone Greenphone {self.model} is upgraded to Android Version:{self.version}')
            else:
                print(f'Your phone Greenphone {self.model} is already up to date')
        elif self.model[0]=='U':
            if self.count<self.u:
                self.version+=1
                self.count+=1
                print(f'Your phone Greenphone {self.model} is upgraded to Android Version:{self.version}')
            else:
                print(f'Your phone Greenphone {self.model} is already up to date')

    def showSpecification(self):
        print("Phone Company:", self.phone_company)
        print("Model Name:", self.model)
        print("Android Version:", self.version)
        print("Number of Cameras:", self.camera)
print('1=======================')
p1 = GreenPhone('A1', 12, 3)
p2 = GreenPhone('M11', 12, 4)
p3 = GreenPhone('U20', 12, 5)
p1.showSpecification()
print('2=======================')
p2.showSpecification()
print('3=======================')
p1.updatePhone()
print('4=======================')
p1.updatePhone()
p2.updatePhone()
p3.updatePhone()
print('5=======================')
p1.updatePhone()
p2.updatePhone()
p3.updatePhone()
print('6=======================')
p2.updatePhone()
p3.updatePhone()
print('7=======================')
p1.showSpecification()
p3.showSpecification()

1=======================
Phone Company: Green Phone
Model Name: A1
Android Version: 12
Number of Cameras: 3
2=======================
Phone Company: Green Phone
Model Name: M11
Android Version: 12
Number of Cameras: 4
3=======================
Your phone Greenphone A1 is upgraded to Android Version:13
4=======================
Your phone Greenphone A1 is already up to date
Your phone Greenphone M11 is upgraded to Android Version:13
Your phone Greenphone U20 is upgraded to Android Version:13
5=======================
Your phone Greenphone A1 is already up to date
Your phone Greenphone M11 is upgraded to Android Version:14
Your phone Greenphone U20 is upgraded to Android Version:14
6=======================
Your phone Greenphone M11 is already up to date
Your phone Greenphone U20 is upgraded to Android Version:15
7=======================
Phone Company: Green Phone
Model Name: A1
Android Version: 13
Number of Cameras: 3
Phone Company: Green Phone
Model Name: U20
Android Version: 15
Number of Cameras: 5

In [ ]:
class StudentDatabase :
    def __init__(self,name,id):
        self.name=name
        self.id=id
        self.grades={}

    def calculateGPA(self,infos,semester):
        self.semester=semester
        self.grades[self.semester]={}
        self.cg=0
        self.course=[]
        sum=0
        for i in infos:
            course,cg= i.split(':')
            sum+=3*float(cg)
            self.course.append(course)
        totalcg=sum/(3*len(infos))
        self.cg=totalcg
        self.grades[self.semester][tuple(self.course)]=self.cg
    def printDetails(self):
        print("Name:", self.name)
        print("ID:", self.id)
        for semester,courses in self.grades.items():
            print(f"Courses taken in {semester}:")
            for tup,cg in courses.items():
                for i in tup:
                    print(i)
                print(cg)

# Write your code here
s1 = StudentDatabase('Pietro', '10101222')
s1.calculateGPA(['CSE230: 4.0', 'CSE220: 4.0', 'MAT110: 4.0'], 'Summer2020')
s1.calculateGPA(['CSE250: 3.7', 'CSE330: 4.0'], 'Summer2021')
print(f'Grades for {s1.name}\n{s1.grades}')
print('---------------------------------')
s1.printDetails()
s2 = StudentDatabase('Wanda', '10103332')
s2.calculateGPA(['CSE111: 3.7', 'CSE260: 3.7', 'ENG101: 4.0'], 'Summer2022')
print('---------------------------------')
print(f'Grades for {s2.name}\n{s2.grades}')
print('---------------------------------')
s2.printDetails()

Grades for Pietro
{'Summer2020': {('CSE230', 'CSE220', 'MAT110'): 4.0}, 'Summer2021': {('CSE250', 'CSE330'): 3.85}}
---------------------------------
Name: Pietro
ID: 10101222
Courses taken in Summer2020:
CSE230
CSE220
MAT110
4.0
Courses taken in Summer2021:
CSE250
CSE330
3.85
---------------------------------
Grades for Wanda
{'Summer2022': {('CSE111', 'CSE260', 'ENG101'): 3.8000000000000003}}
---------------------------------
Name: Wanda
ID: 10103332
Courses taken in Summer2022:
CSE111
CSE260
ENG101
3.8000000000000003

In [ ]:
class Scope:
    def __init__(self):
        self.x, self.y = 1, 100
    def met1(self):
        x = 3
        x = self.x + 1
        self.y = self.y + self.x + 1
        x = self.y + self.met2() + self.y
        print(x, self.y)
    def met2(self):
        y = 0
        print(self.x, y)
        self.x = self.x + y
        self.y = self.y + 200
        return self.x + y

q2 = Scope()
q2.met1()
q2.met2()
q2.met1()
q2.met2()

1 0
405 302
1 0
1 0
1209 704
1 0

1

In [ ]:
class Farmer:
    def __init__(self,n=None):
        if n==None:
            print('Welcome to your farm')
        elif type(n)==str:
            print('Welcome to your farm',n)
        elif type(n)==int:
            print(f'Welcome to your farm your farm id is{n} ')
        self.crop=[]
        self.fish=[]

    def addCrops(self,*c):
        if len(c)==0:
            print(f'0 crops were added')
        else:
            print(f'{len(c)} crops were added')
            self.crop+=c

    def addFishes(self,*f):
        if len(f)==0:
            print(f'0 fishes were added')
        else:
            print(f'{len(f)} fishes were added')
            self.fish+=f

    def showGoods(self):
        if len(self.crop)==0:
            print("You don't have any crops")
        else:
            print(f"You have {len(self.crop)} crops ")
            for i in range(len(self.crop)):
                if i==len(self.crop)-1:
                    print(self.crop[i],end=' ')
                    print()
                else:
                    print(self.crop[i],end=',')

        if len(self.fish)==0:
            print("You don't have any fishes")
        else:
            print(f"You have {len(self.fish)} fishes ")
            for i in range(len(self.fish)):
                if i==len(self.fish)-1:
                    print(self.fish[i],end=' ')
                    print()
                else:
                    print(self.fish[i],end=',')

f1 = Farmer()
print("-------------------")
f1.addCrops('Rice', "Jute", "Cinnamon")
print("-------------------")
f1.addFishes()
print("-------------------")
f1.addCrops('Mustard')
print("-------------------")
f1.showGoods()
print("-------------------")
f2 = Farmer("Korim Mia")
print("-------------------")
f2.addFishes('Pangash', 'Magur')
print("-------------------")
f2.addCrops("Wheat", "Potato")
print("-------------------")
f2.addFishes("Koi", "Tuna", "Sardine")
print("-------------------")
f2.showGoods()
print("-------------------")
f3 = Farmer(2865127000)
print("-------------------")
f3.addCrops()
print("-------------------")
f3.addFishes("Katla")
print("-------------------")
f3.showGoods()
print("------------------")

Welcome to your farm
-------------------
3 crops were added
-------------------
0 fishes were added
-------------------
1 crops were added
-------------------
You have 4 crops
Rice,Jute,Cinnamon,Mustard
You don't have any fishes
-------------------
Welcome to your farm Korim Mia
-------------------
2 fishes were added
-------------------
2 crops were added
-------------------
3 fishes were added
-------------------
You have 2 crops
Wheat,Potato
You have 5 fishes
Pangash,Magur,Koi,Tuna,Sardine
-------------------
Welcome to your farm your farm id is2865127000
-------------------
0 crops were added
-------------------
1 fishes were added
-------------------
You don't have any crops
You have 1 fishes
Katla
------------------

In [ ]:
class TaxiLagbe:
    def __init__(self,taxi_num,location):
        self.taxi_num=taxi_num
        self.location=location
        self.passanger=[]
        self.total=0
    def addPassenger(self,*p):
        for i in p:
            pas,money=i.split('_')
            if len(self.passanger)<4:
                self.total+=int(money)
                self.passanger.append(pas)
                print(f'Dear {pas} welcome to TaxiLagbe')
            else:
                print('Taxi Full! No more passengers can be added.')

    def printDetails(self):
        print(f"Trip info for taxi number : {self.taxi_num}")
        print(f"This taxi can only cover the {self.location} area")
        print(f"Total passengers: {len(self.passanger)}")
        print(f"Passenger List:", ','.join(self.passanger))
        print(f"Total collected fare : {self.total}")


taxi1 = TaxiLagbe('1010-01', 'Dhaka')
print('-------------------------------')
taxi1.addPassenger('Walker_100', 'Wood_200','Matt_100')
taxi1.addPassenger('Wilson_105')
print('-------------------------------')
taxi1.printDetails()
print('-------------------------------')
taxi1.addPassenger('Karen_200')
print('-------------------------------')
taxi1.printDetails()
print('-------------------------------')
taxi2 = TaxiLagbe('1010-02', 'Khulna')
taxi2.addPassenger('Ronald_115', 'Parker_215')
print('-------------------------------')
taxi2.printDetails()

-------------------------------
Dear Walker welcome to TaxiLagbe
Dear Wood welcome to TaxiLagbe
Dear Matt welcome to TaxiLagbe
Dear Wilson welcome to TaxiLagbe
-------------------------------
Trip info for taxi number : 1010-01
This taxi can only cover the Dhaka area
Total passengers: 4
Passenger List: Walker,Wood,Matt,Wilson
Total collected fare : 505
-------------------------------
Taxi Full! No more passengers can be added.
-------------------------------
Trip info for taxi number : 1010-01
This taxi can only cover the Dhaka area
Total passengers: 4
Passenger List: Walker,Wood,Matt,Wilson
Total collected fare : 505
-------------------------------
Dear Ronald welcome to TaxiLagbe
Dear Parker welcome to TaxiLagbe
-------------------------------
Trip info for taxi number : 1010-02
This taxi can only cover the Khulna area
Total passengers: 2
Passenger List: Ronald,Parker
Total collected fare : 330

In [ ]:
class  Sphere:
    def __init__(self,name,r=1,color='White'):
        self.name=name
        self.r=r
        self.color=color
        self.volume= (4/3)*3.1416*(r**3)
        self.c=[]

    def printDetails(self):
        print(f"Sphere id : {self.name}")
        print(f"color: {self.color}")
        print(f"Volume: {self.volume}")

    def merge_sphere(self,*s):
        print('Spheres are being merged')
        for i in s:
            self.volume+=i.volume
            if i.color != self.color:
                self.color='Mixed color'
sphere1 = Sphere("Sphere 1")
print("1***************")
sphere1.printDetails()
print("2***************")
sphere2 = Sphere("Sphere 2", 3)
print("3***************")
sphere2.printDetails()
print("4***************")
sphere3 = Sphere("Sphere 3", 2)
print("5***************")
sphere3.printDetails()
print("6***************")
sphere3.merge_sphere(sphere1,sphere2)
print("7***************")
sphere3.printDetails()
print("8***************")
sphere4 = Sphere("Sphere 4", 5, "Purple")
print("9***************")
sphere4.merge_sphere(sphere3)
print("10***************")
sphere4.printDetails()

1***************
Sphere id : Sphere 1
color: White
Volume: 4.1888
2***************
3***************
Sphere id : Sphere 2
color: White
Volume: 113.09759999999999
4***************
5***************
Sphere id : Sphere 3
color: White
Volume: 33.5104
6***************
Spheres are being merged
7***************
Sphere id : Sphere 3
color: White
Volume: 150.7968
8***************
9***************
Spheres are being merged
10***************
Sphere id : Sphere 4
color: Mixed color
Volume: 674.3967999999999

In [ ]:
class  Foodie:
    def __init__(self,name):
        self.name=name
        self.items=[]
        self.total=0

    def show_orders(self):
        return f"{self.name} has {len(self.items)} items in the cart \nItems : {self.items} \nTotal Spent: {self.total}"

    def order(self,*food):
        for i in food:
            name,quantity= i.split('-')
            self.items.append(name)
            total=0
            if name in menu:
                total=menu[name]*int(quantity)
                self.total+=total
            print(f"Ordered - {name}, Quantity - {quantity}, price per unit - {menu[name]}")
            print('Total Price - ',total)
    def pay_tips(self,amount=None):
        if amount == None :
            print('No tips to the waiter')
        else:
            print(f"Gives {amount}/- tips to the waiter.")
            self.total+=amount

menu = {'Chicken Lollipop':15,'Beef Nugget':20,'Americano':180,'Red Velvet':150,'Prawn Tempura':80,'Saute Veg':200}


f1 = Foodie('Frodo')
print(f1.show_orders())
print('1----------------------')
f1.order('Chicken Lollipop-3','Beef Nugget-6','Americano-1')
print('2----------------------')
print(f1.show_orders())
print('3----------------------')
f1.order('Red Velvet-1')
print('4----------------------')
f1.pay_tips(20)
print('5----------------------')
print(f1.show_orders())
f2 = Foodie('Bilbo')
print('6----------------------')
f2.order('Prawn Tempura-6','Saute Veg-1')
print('7----------------------')
f2.pay_tips()
print('8----------------------')
print(f2.show_orders())

Frodo has 0 items in the cart
Items : []
Total Spent: 0
1----------------------
Ordered - Chicken Lollipop, Quantity - 3, price per unit - 15
Total Price -  45
Ordered - Beef Nugget, Quantity - 6, price per unit - 20
Total Price -  120
Ordered - Americano, Quantity - 1, price per unit - 180
Total Price -  180
2----------------------
Frodo has 3 items in the cart
Items : ['Chicken Lollipop', 'Beef Nugget', 'Americano']
Total Spent: 345
3----------------------
Ordered - Red Velvet, Quantity - 1, price per unit - 150
Total Price -  150
4----------------------
Gives 20/- tips to the waiter.
5----------------------
Frodo has 4 items in the cart
Items : ['Chicken Lollipop', 'Beef Nugget', 'Americano', 'Red Velvet']
Total Spent: 515
6----------------------
Ordered - Prawn Tempura, Quantity - 6, price per unit - 80
Total Price -  480
Ordered - Saute Veg, Quantity - 1, price per unit - 200
Total Price -  200
7----------------------
No tips to the waiter
8----------------------
Bilbo has 2 items in the cart
Items : ['Prawn Tempura', 'Saute Veg']
Total Spent: 680

In [ ]:
class Department:
    def __init__(self,name='ChE',sections=5):
        self.name=name
        self.sections=sections
        print(f'The {self.name} department has {self.sections} sections')
        self.avg=0
    def add_students(self,*st):
        total=0
        if len(st)==self.sections:
            for i in st:
                total+=int(i)
            self.avg=total/self.sections
            print(f"THe {self.name} department has an average of {self.avg} students in each sections")
        else:
            print(f"The {self.name} department doesn't have {len(st)} sections ")

    def merge_Department(self,*s1):
        sum=0
        for i in s1:
            print(f'{i.name} is merged to {self.name}.')
            sum+=(i.avg*i.sections)
        self.avg=((self.avg*self.sections)+sum)/(self.sections)
        return f'Now the {self.name} has an average of {self.avg:.2f} students in each section.'

d1 = Department()
print('1-----------------------------')
d2 = Department('MME Department')
print('2-----------------------------')
d3 = Department('NCE Department', 8)
print('3-----------------------------')
d1.add_students(12, 23, 12, 34, 21)
print('4-----------------------------')
d2.add_students(40, 30, 21)
print('5-----------------------------')
d3.add_students(12, 34, 41, 17, 30, 22, 32, 51)
print('6-----------------------------')
mega = Department('Engineering Department', 10)
print('7-----------------------------')
mega.add_students(21,30,40,36,10,32,27,51,45,15)
print('8-----------------------------')
print(mega.merge_Department(d1, d2))
print('9-----------------------------')
print(mega.merge_Department(d3))

The ChE department has 5 sections
1-----------------------------
The MME Department department has 5 sections
2-----------------------------
The NCE Department department has 8 sections
3-----------------------------
THe ChE department has an average of 20.4 students in each sections
4-----------------------------
The MME Department department doesn't have 3 sections
5-----------------------------
THe NCE Department department has an average of 29.875 students in each sections
6-----------------------------
The Engineering Department department has 10 sections
7-----------------------------
THe Engineering Department department has an average of 30.7 students in each sections
8-----------------------------
ChE is merged to Engineering Department.
MME Department is merged to Engineering Department.
Now the Engineering Department has an average of 40.90 students in each section.
9-----------------------------
NCE Department is merged to Engineering Department.
Now the Engineering Department has an average of 64.80 students in each section.

In [ ]:
class Shopidify:
    def __init__(self,name='Guest'):
        self.n = name
        if self.n != 'Guest':
            print(f'Welcome {self.n} to Shopidify')
        else:
            print('Welcome to Shopidify')
        self.d = {}

    def add_to_cart(self,item,amount=1):
        if type(item) == str:
            if item not in self.d:
                self.d[item] = amount
            else:
                self.d[item] += amount

        elif type(item) == list:
            for i in range(len(item) - 1):
                if type(item[i]) == str and type(item[i + 1]) == int:
                    if item[i] not in self.d:
                        self.d[item[i]] = item[i + 1]
                    else:
                        self.d[item[i]] += item[i + 1]

    def display_cart(self):
        print(f'Items in the cart for {self.n}')
        for i,j in self.d.items():
            print(f"- {i}: {j}X")

    def display_history(self):
        print(f"Purchase history for {self.n}")
        print(f"Transaction 1:")
        for i,j in self.d.items():
            print(f"- {i}: {j}X")

    def checkout(self):
        print(f'Checkout completed for {self.n}')
guest_account = Shopidify()
print("1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
john_account = Shopidify("John")
print("2xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
guest_account.add_to_cart("Air Jordan", 2)
guest_account.add_to_cart("Luffy Action Figure")
guest_account.display_cart()
print("3xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
john_account.add_to_cart(["Chocolate Chip Cookies", 3,"Goku Action Figure",2,"Dumbbells-5kg",2])
john_account.display_cart()
print("4xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
guest_account.add_to_cart("Air Jordan")
guest_account.display_cart()
print("5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
guest_account.checkout()
print("6xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
guest_account.display_history()
print("7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
john_account.checkout()
print("8xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
john_account.display_history()
print("9xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")

Welcome to Shopidify
1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Welcome John to Shopidify
2xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Items in the cart for Guest
- Air Jordan: 2X
- Luffy Action Figure: 1X
3xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Items in the cart for John
- Chocolate Chip Cookies: 3X
- Goku Action Figure: 2X
- Dumbbells-5kg: 2X
4xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Items in the cart for Guest
- Air Jordan: 3X
- Luffy Action Figure: 1X
5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Checkout completed for Guest
6xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Purchase history for Guest
Transaction 1:
- Air Jordan: 3X
- Luffy Action Figure: 1X
7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Checkout completed for John
8xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Purchase history for John
Transaction 1:
- Chocolate Chip Cookies: 3X
- Goku Action Figure: 2X
- Dumbbells-5kg: 2X
9xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

In [ ]:
class Spaceship:
    def __init__(self,Name,Capacity):
        self.name=Name
        self.capacity=Capacity
        self.cargos=[]
        self.current_cargo_weight=0

    def load_cargo(self,carg):
        if carg.weight+self.current_cargo_weight <= self.capacity:
            self.cargos.append(carg.material)
            self.current_cargo_weight+=carg.weight
        else:
            exceed= (self.current_cargo_weight+carg.weight)-self.capacity
            print(f"Warning! unable to load {carg.material} it exceeds by {exceed}")

    def display_details(self):
        print("Spaceship Name:", self.name)
        print("Capacity:", self.capacity)
        print("Current Cargo Weight:", self.current_cargo_weight)
        # for i in self.cargo:
        #   print(i.get_name())
        print("Cargo:", self.cargos)


class Cargo:
    def __init__(self,material,weight):
        self.material=material
        self.weight=weight

falcon = Spaceship("Falcon", 50000)
apollo = Spaceship("Apollo", 100000)
enterprise = Spaceship("Enterprise", 220000)
print("1.===================================")

gold = Cargo("Gold", 20000)
platinum = Cargo("Platinum", 25000)
dilithium = Cargo("Dilithium", 50000)
trilithium = Cargo("Trilithium", 70000)
neutronium = Cargo("Neutronium", 80000)
print("2.===================================")

falcon.load_cargo(gold)
falcon.load_cargo(platinum)
falcon.display_details()
print("3.===================================")

apollo.load_cargo(gold)
apollo.display_details()
print("4.===================================")

falcon.load_cargo(neutronium)
print("5.===================================")

enterprise.load_cargo(dilithium)
enterprise.load_cargo(trilithium)
enterprise.load_cargo(neutronium)
enterprise.display_details()

1.===================================
2.===================================
Spaceship Name: Falcon
Capacity: 50000
Current Cargo Weight: 45000
Cargo: ['Gold', 'Platinum']
3.===================================
Spaceship Name: Apollo
Capacity: 100000
Current Cargo Weight: 20000
Cargo: ['Gold']
4.===================================
Warning! unable to load Neutronium it exceeds by 75000
5.===================================
Spaceship Name: Enterprise
Capacity: 220000
Current Cargo Weight: 200000
Cargo: ['Dilithium', 'Trilithium', 'Neutronium']

In [ ]:
class RickMote:
  def __init__(self):
    self.power_status=False
    self.ch_list=[0,2,3,6,7,9]
    self.current_ch_indx=0
    self.vol=3
  def power(self):
    self.power_status=not self.power_status

  def changeChannel(self,ch=None):

    if self.power_status==True:
        if ch == None:
            if self.current_ch_indx==5:
                print('Cannot go beyond this')
            else:
                self.current_ch_indx+=1

        elif ch in self.ch_list:
            self.current_ch_index = self.ch_list.index(ch)
        else:
            print('Channel Does not Exist')
    else:
        print('Power is off')

  def changeVolumeLevel(self, level=None):
    if self.power_status:
      if level==None:
        self.vol+=1
      else:
        self.vol+=level
    else:
      print("Power is turned off. Cannot change volume.")

  def showInfo(self):
      print("ID cable box status")
      if self.power_status:
        print("Cable box is:ON")
        print("Channel", self.ch_list[self.current_ch_indx])
        print("Volume", self.vol)
      else:
        print("Cable box is:OFF")


oTV = RickMote()
oTV.power()
print("1.############################")
oTV.showInfo()
print("2.############################")
oTV.changeChannel()
oTV.changeVolumeLevel()
oTV.showInfo()
print("3.############################")
oTV.power()
oTV.showInfo()
print("4.############################")
oTV.power()
oTV.changeVolumeLevel(4)
oTV.changeChannel(3)
oTV.showInfo()
print("5.############################")
oTV.changeVolumeLevel(-2)
oTV.showInfo()
print("6.############################")
oTV.power()
oTV.changeChannel(9)
oTV.changeVolumeLevel(-1)
oTV.showInfo()
print("7.############################")
oTV.power()
oTV.changeChannel(11)
oTV.showInfo()

1.############################
ID cable box status
Cable box is:ON
Channel 0
Volume 3
2.############################
ID cable box status
Cable box is:ON
Channel 2
Volume 4
3.############################
ID cable box status
Cable box is:OFF
4.############################
ID cable box status
Cable box is:ON
Channel 2
Volume 8
5.############################
ID cable box status
Cable box is:ON
Channel 2
Volume 6
6.############################
Power is off
Power is turned off. Cannot change volume.
ID cable box status
Cable box is:OFF
7.############################
Channel Does not Exist
ID cable box status
Cable box is:ON
Channel 2
Volume 6

In [ ]:
class PizzaMachine:
    def __init__(self,Type='Regular',size=6):
        self.Type=Type
        self.size=size
        self.spices=['Regular','Hot','Super Naga']

    def customizePizza(self,toppings,spice='Regular'):
        self.toppings=toppings
        self.spice=spice
        if type(toppings)!=list:
            x = f"No toppings specified! Can't bake pizza."

        elif self.spice not in self.spices:
            x= "Sorry! Spice level not allowed. Can't bake pizza."
        else:
            join= ','.join(self.toppings)
            x = f"Your {self.size} {self.spice} spicey {self.Type} pizza is ready with {join} toppings enjoy"
        return x

pizza1 = PizzaMachine()
order1 = pizza1.customizePizza(["Cheese", "Pepperoni"],
"Hot")
print("1################################# ")
print(order1)
print("2================================")
pizza2 = PizzaMachine("Vege")
order2 = pizza2.customizePizza("Super Naga")
print("3#################################")
print(order2)
print("4================================")
pizza3 = PizzaMachine("Chicken Blast",12)
order3 = pizza3.customizePizza(["Mushroom"])
print("5#################################")
print(order3)
print("6================================")
pizza4 = PizzaMachine("Beef Bonanza",16)
order4 = pizza4.customizePizza(["Cheese","Beef kalabhuna"],"Mild")
print("7#################################")
print(order4)
print("8================================")

1#################################
Your 6 Hot spicey Regular pizza is ready with Cheese,Pepperoni toppings enjoy
2================================
3#################################
No toppings specified! Can't bake pizza.
4================================
5#################################
Your 12 Regular spicey Chicken Blast pizza is ready with Mushroom toppings enjoy
6================================
7#################################
Sorry! Spice level not allowed. Can't bake pizza.
8================================

In [ ]:
class Student:
    def __init__(self,name,id,cg):
        self.name=name
        self.id=id
        self.cg=cg

    def setId(self,new_id):
        self.id=new_id

class Department:
    def __init__(self,dept):
        self.dept=dept
        self.students=[]

    def addStudent(self,*st):
        for i in st:
            for j in self.students:
                if i.id==j.id:
                    print("Student with the same id already exists please try another id")
                    break
            else:
                self.students.append(i)
                print(f"Welcome to {self.dept} department {i.name}")

    def findStudent(self,s):
        for i in self.students:
            if i.id==s:
                print(f'Student info:')
                print(f'Student Name: {i.name}')
                print(f'Id: {i.id}')
                print(f'CGPA: {i.cg}')
                break
        else:
            print("Student with this ID doesn't exist, Please give a valid ID")

    def details (self):
        print(f'Department Name: {self.dept}')
        print(f'Number of Student:{len(self.students)}')
        print(f'Details of the students:')
        for i in self.students:
            print(f'Student name: {i.name},ID: {i.id}, cgpa:{i.cg} ')


s1 = Student("Akib", 22301010, 3.29)
s2 = Student("Reza", 22101010, 3.45)
s3 = Student("Ruhan", 23101934, 4.00)
print("1==================================")
cse = Department("CSE")
cse.findStudent(22112233)
print("2==================================")
cse.addStudent(s1,s2,s3)
print("3==================================")
cse.details()
print("4==================================")
cse.findStudent(22301010)
print("5==================================")
s4 = Student("Nakib",22301010,3.22)
cse.addStudent(s4)
print("6==================================")
s4.setId(21201220)
cse.addStudent(s4)
print("7==================================")
cse.details()
print("8==================================")
s5 = Student("Sakib",22201010,2.29)
cse.addStudent(s5)
print("9==================================")
cse.details()

1==================================
Student with this ID doesn't exist, Please give a valid ID
2==================================
Welcome to CSE department Akib
Welcome to CSE department Reza
Welcome to CSE department Ruhan
3==================================
Department Name: CSE
Number of Student:3
Details of the students:
Student name: Akib,ID: 22301010, cgpa:3.29
Student name: Reza,ID: 22101010, cgpa:3.45
Student name: Ruhan,ID: 23101934, cgpa:4.0
4==================================
Student info:
Student Name: Akib
Id: 22301010
CGPA: 3.29
5==================================
Student with the same id already exists please try another id
6==================================
Welcome to CSE department Nakib
7==================================
Department Name: CSE
Number of Student:4
Details of the students:
Student name: Akib,ID: 22301010, cgpa:3.29
Student name: Reza,ID: 22101010, cgpa:3.45
Student name: Ruhan,ID: 23101934, cgpa:4.0
Student name: Nakib,ID: 21201220, cgpa:3.22
8==================================
Welcome to CSE department Sakib
9==================================
Department Name: CSE
Number of Student:5
Details of the students:
Student name: Akib,ID: 22301010, cgpa:3.29
Student name: Reza,ID: 22101010, cgpa:3.45
Student name: Ruhan,ID: 23101934, cgpa:4.0
Student name: Nakib,ID: 21201220, cgpa:3.22
Student name: Sakib,ID: 22201010, cgpa:2.29

In [ ]:
class Vaccine:
    def __init__(self,n,c,d):
        self.n=n
        self.c=c
        self.d=d

class Person:
    def __init__(self,name,age,Type="General Citizen"):
        self.name=name
        self.age=age
        self.Type=Type
        self.vaccine=None
        self.x=False


    def pushVaccine(self,v,Dose='First Dose'):
        if Dose == 'First Dose':
            if self.age>=25 or self.Type=='Student':
                print('First Dose done for',self.name)
                self.vaccine=v
                self.x=True
            else:
                print ("sorry",self.name ,"minimum age for vaccination is 25")
        else:
            if v.n==self.vaccine.n:
                print('Second Dose done for',self.name)
            else:
                print('You cant take two different vaccines')
                self.x=False

    def showDetail(self):
        print("Name :",self.name ,"Age:",self.age,"Type:",self.Type)
        print("Vaccine Name:",self.vaccine.n)

        if self.x==True:
            print('1st Dose: Done')
            print('2nd Dose: Please come after',self.vaccine.d,'days')
        else:
             print("First dose done")
             print("Second dose done")

astra = Vaccine("AstraZeneca", "UK", 60)
modr = Vaccine("Moderna", "UK", 30)
sin = Vaccine("Sinopharm", "China", 30)
p1 = Person("Bob", 21, "Student")
print("=================================")
p1.pushVaccine(astra)
print("=================================")
p1.showDetail()
print("=================================")
p1.pushVaccine(sin, "2nd Dose")
print("=================================")
p1.pushVaccine(astra, "2nd Dose")
print("=================================")
p1.showDetail()
print("=================================")
p2 = Person("Carol", 23, "Actor")
print("=================================")
p2.pushVaccine(sin)
print("=================================")
p3 = Person("David", 34)
print("=================================")
p3.pushVaccine(modr)
print("=================================")
p3.showDetail()
print("=================================")
p3.pushVaccine(modr, "2nd Dose")

=================================
First Dose done for Bob
=================================
Name : Bob Age: 21 Type: Student
Vaccine Name: AstraZeneca
1st Dose: Done
2nd Dose: Please come after 60 days
=================================
You cant take two different vaccines
=================================
Second Dose done for Bob
=================================
Name : Bob Age: 21 Type: Student
Vaccine Name: AstraZeneca
First dose done
Second dose done
=================================
=================================
sorry Carol minimum age for vaccination is 25
=================================
=================================
First Dose done for David
=================================
Name : David Age: 34 Type: General Citizen
Vaccine Name: Moderna
1st Dose: Done
2nd Dose: Please come after 30 days
=================================
Second Dose done for David

In [ ]:
#task 3
class Vaccine :
    def __init__(self,name,made_in,interval):
        self.name = name
        self.made_in = made_in
        self.interval = interval
class Person:
    def __init__(self,pname,age,Type = "General Person"):
        self.pname = pname
        self.age = age
        self.Type = Type
        self.vac = ""
        self.First_Dose = False
        self.Second_Dose = False

    def pushVaccine(self, vac_name, dose = "First Dose"):
        if dose == "First Dose" :
            if (self.age >= 25 or self.Type == "Student"):
                self.First_Dose = True
                self.vac = vac_name
                print("1st dose done for",self.pname)
            else:
                print ("sorry",self.pname ,"minimum age for vaccination is 25")

        else:
            if (self.vac.name != vac_name.name):
                    print("cannot give 2 different vaccines")
            else:
                print("second dose done for",self.pname)
                self.Second_Dose == True
    def showDetail(self):
        print("Name :",self.pname ,"Age:",self.age,"Type:",self.Type)
        print("Vaccine Name:",self.vac.name)

        if(self.Second_Dose == True):
            print("First dose done")
            print("Second dose done")
        elif(self.First_Dose == True):
            print("Fist dose done")
            print("One dose given come after getting", self.vac.interval)
astra = Vaccine("AstraZeneca", "UK", 60)
modr = Vaccine("Moderna", "UK", 30)
sin = Vaccine("Sinopharm", "China", 30)
p1 = Person("Bob", 21, "Student")
print("=================================")
p1.pushVaccine(astra)
print("=================================")
p1.showDetail()
print("=================================")
p1.pushVaccine(sin, "2nd Dose")
print("=================================")
p1.pushVaccine(astra, "2nd Dose")
print("=================================")
p1.showDetail()
print("=================================")
p2 = Person("Carol", 23, "Actor")
print("=================================")
p2.pushVaccine(sin)
print("=================================")
p3 = Person("David", 34)
print("=================================")
p3.pushVaccine(modr)
print("=================================")
p3.showDetail()
print("=================================")
p3.pushVaccine(modr, "2nd Dose")

=================================
1st dose done for Bob
=================================
Name : Bob Age: 21 Type: Student
Vaccine Name: AstraZeneca
Fist dose done
One dose given come after getting 60
=================================
cannot give 2 different vaccines
=================================
second dose done for Bob
=================================
Name : Bob Age: 21 Type: Student
Vaccine Name: AstraZeneca
Fist dose done
One dose given come after getting 60
=================================
=================================
sorry Carol minimum age for vaccination is 25
=================================
=================================
1st dose done for David
=================================
Name : David Age: 34 Type: General Person
Vaccine Name: Moderna
Fist dose done
One dose given come after getting 30
=================================
second dose done for David

In [ ]:
class MidB:
    def __init__(self):
        self.x = 3
        self.y = 0
        self.sum = 5
    def methodA(self, x):

        self.y = self.sum + self.x + x
        self.sum = x + self.y
        d = MidB()
        d.sum = self.sum + self.methodB(d)
        print(self.x, self.y, self.sum)
    def methodB(self, t, z=0):
        y = 3
        t.x = self.x + self.sum
        self.sum = t.x + t.y + y
        print(t.x, t.y, t.sum)
        if z == 0:
            return t.sum

b=MidB()
b.methodA(6)
b.methodB(b,99)

23 0 5
3 14 26
29 14 46

In [ ]:
class MidB:
    def __init__(self):
        self.y,self.z,self.sum = 3,2,-1
    def m1(self, mg2, mg1=2):
        x = 0
        self.y = self.y + mg2[0]
        x += 23 + mg1
        self.sum += x + self.y
        mg2[0] = self.y + mg1
        mg1 = mg1 + x + 4
        print(x, self.y, self.sum)
    def m2(self, y=3):
        mid = [0]
        mid[0] = 5
        self.m1(mid, mid[0])
        z = y + mid[0]
        y = self.y + mid[0]
        self.sum = z + y + mid[0]
        print(z, y, self.sum)

a = MidB()
a.m1([8])
a.m2()

25 11 35
28 16 79
24 37 82

class method

In [ ]:
class Employee:
  org_name='Google'
  def __init__(self,id,name):
    self.id=id
    self.name=name
  @classmethod
  def change_info(cls):
    cls.org_name='Amazon'
    return cls.org_name
  @classmethod
  def create_from_string(cls, text):
    id,name=text.split("-")

    obj=cls(id,name)
    return obj

print(Employee.change_info())
S1=Employee.create_from_string("22-Sam")
print(S1.id)
print(S1.name)

Amazon
22
Sam

In [ ]:
class Student:
    ID=1
    def __init__(self,name,dept,age,cg):
        self.name=name
        self.dept=dept
        self.age=age
        self.cg=cg
        Student.ID+=1

    def showDetails(self):
        print(f"ID: {Student.ID}")
        print(f'Department: {self.dept}')
        print(f"Name:{self.name}")
        print(f"Age:{self.age}")
        print(f"CGPA:{self.cg}")


    @classmethod
    def from_String(cls,details):
       name, department, age, cgpa =details.split('-')
       obj=cls(name, department, int(age), float(cgpa))
       return obj

s1 = Student("Samin", "CSE", 21, 3.91)
s1.showDetails()
print("-----------------------")
s2 = Student("Fahim", "ECE", 21, 3.85)
s2.showDetails()
print("-----------------------")
s3 = Student("Tahura", "EEE", 22, 3.01)
s3.showDetails()
print("-----------------------")
s4 = Student.from_String("Sumaiya-BBA-23-3.96")
s4.showDetails()

ID: 2
Department: CSE
Name:Samin
Age:21
CGPA:3.91
-----------------------
ID: 3
Department: ECE
Name:Fahim
Age:21
CGPA:3.85
-----------------------
ID: 4
Department: EEE
Name:Tahura
Age:22
CGPA:3.01
-----------------------
ID: 5
Department: BBA
Name:Sumaiya
Age:23
CGPA:3.96

In [ ]:
class NikeBangladesh:
    BranchesOpened=[]
    CurrentlyStocked={'Air Jordan':0,'Cortez':0,'Zoom Kobe':0}
    sold=0
    def __init__(self,location):
        self.__location=location
        self.__BranchesOpened=[]
        self.__inventory={'Air Jordan':0,'Cortez':0,'Zoom Kobe':0}
        self.__Sold=0
        NikeBangladesh.BranchesOpened.append(self.__location)
    def details(self):
        print(f'Nike DHAKA {self.__location} outlet')
        print(f'Products Currently Stocked {self.__inventory}')
        print(f'Sold:{self.__Sold}')

    def productSold(self,p):
        for i,j in p.items():
            if self.__inventory[i]>=j:
                self.__inventory[i]-=j
                self.__Sold+=j
                NikeBangladesh.CurrentlyStocked[i] -= j
                NikeBangladesh.sold+=j
            else:
                print(f"Not enough stock of {i} in {self._location} outlet.")


    def restockProducts(self, restock_dict):
        for product, quantity in restock_dict.items():
            self.__inventory[product] += quantity
            NikeBangladesh.CurrentlyStocked[product] += quantity

    @classmethod
    def status(cls):
        print("Nike Bangladesh Status:")
        print("Branches Opened:", cls.BranchesOpened)
        print("Currently Stocked")
        print(cls.CurrentlyStocked)


# Driver code
print("xxxxxxxxxxxxxx1xxxxxxxxxxxxxxxx")
NikeBangladesh.status()
dhaka = NikeBangladesh("Dhaka Banani")
chittagong = NikeBangladesh("Chittagong GEC")
print("xxxxxxxxxxxxxx2xxxxxxxxxxxxxxxx")
dhaka.details()
print("xxxxxxxxxxxxxx3xxxxxxxxxxxxxxxx")
chittagong.details()
print("xxxxxxxxxxxxxx4xxxxxxxxxxxxxxxx")
dhaka.restockProducts({"Air Jordan": 1200, "Cortez": 200, "Zoom Kobe": 200})
chittagong.restockProducts({"Air Jordan": 1000, "Cortez": 250, "Zoom Kobe": 100})
print("xxxxxxxxxxxxxx5xxxxxxxxxxxxxxxx")
NikeBangladesh.status()
print("xxxxxxxxxxxxxx6xxxxxxxxxxxxxxxx")
dhaka.productSold({"Air Jordan": 760, "Cortez": 90})
chittagong.productSold({"Air Jordan": 520, "Zoom Kobe": 70})
print("xxxxxxxxxxxxxx7xxxxxxxxxxxxxxxx")
NikeBangladesh.status()

xxxxxxxxxxxxxx1xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened: []
Currently Stocked
{'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
xxxxxxxxxxxxxx2xxxxxxxxxxxxxxxx
Nike DHAKA Dhaka Banani outlet
Products Currently Stocked {'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold:0
xxxxxxxxxxxxxx3xxxxxxxxxxxxxxxx
Nike DHAKA Chittagong GEC outlet
Products Currently Stocked {'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold:0
xxxxxxxxxxxxxx4xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxx5xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened: ['Dhaka Banani', 'Chittagong GEC']
Currently Stocked
{'Air Jordan': 2200, 'Cortez': 450, 'Zoom Kobe': 300}
xxxxxxxxxxxxxx6xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxx7xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened: ['Dhaka Banani', 'Chittagong GEC']
Currently Stocked
{'Air Jordan': 920, 'Cortez': 360, 'Zoom Kobe': 230}

In [ ]:
class NikeBangladesh:
    Branches_opened=[]
    CurrentlyStocked={'Air Jordan':0,'Cortez':0,'Zoom Kobe':0}
    sold=0
    def __init__(self,location):
        self.__location=location
        self.__l=[]
        self.__d={'Air Jordan':0,'Cortez':0,'Zoom Kobe':0}
        self.__sold=0

    def details(self):
        print(f'Nike Dhaka {self.__location} outlet')
        print(f'Products currently stocked:')
        print(self.__d)
        print(f'sold: {self.__sold}')

    def restockProducts(self,d):
        for product,quantity in d.items():
            self.__d[product]+=quantity
            NikeBangladesh.CurrentlyStocked[product]+=quantity
    def productSold(self,d1):
        for product,quantity in d1.items():
            if product in self.__d:
                if quantity <= self.__d[product]:
                    self.__d[product]-=quantity
                    self.__sold+=quantity
                    NikeBangladesh.CurrentlyStocked[product] -= quantity
                    NikeBangladesh.sold+=quantity
    @classmethod
    def status(cls):
        print(f'Branches Opened:{cls.Branches_opened}')
        print(f'Products currently stocked:')
        print(cls.CurrentlyStocked)
        print(f'sold: {cls.sold}')
# Driver code
print("xxxxxxxxxxxxxx1xxxxxxxxxxxxxxxx")
NikeBangladesh.status()
dhaka = NikeBangladesh("Dhaka Banani")
chittagong = NikeBangladesh("Chittagong GEC")
print("xxxxxxxxxxxxxx2xxxxxxxxxxxxxxxx")
dhaka.details()
print("xxxxxxxxxxxxxx3xxxxxxxxxxxxxxxx")
chittagong.details()
print("xxxxxxxxxxxxxx4xxxxxxxxxxxxxxxx")
dhaka.restockProducts({"Air Jordan": 1200, "Cortez": 200, "Zoom Kobe": 200})
chittagong.restockProducts({"Air Jordan": 1000, "Cortez": 250, "Zoom Kobe": 100})
print("xxxxxxxxxxxxxx5xxxxxxxxxxxxxxxx")
NikeBangladesh.status()
print("xxxxxxxxxxxxxx6xxxxxxxxxxxxxxxx")
dhaka.productSold({"Air Jordan": 760, "Cortez": 90})
chittagong.productSold({"Air Jordan": 520, "Zoom Kobe": 70})
print("xxxxxxxxxxxxxx7xxxxxxxxxxxxxxxx")
NikeBangladesh.status()

xxxxxxxxxxxxxx1xxxxxxxxxxxxxxxx
Branches Opened:[]
Products currently stocked:
{'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
sold: 0
xxxxxxxxxxxxxx2xxxxxxxxxxxxxxxx
Nike Dhaka Dhaka Banani outlet
Products currently stocked:
{'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
sold: 0
xxxxxxxxxxxxxx3xxxxxxxxxxxxxxxx
Nike Dhaka Chittagong GEC outlet
Products currently stocked:
{'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
sold: 0
xxxxxxxxxxxxxx4xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxx5xxxxxxxxxxxxxxxx
Branches Opened:[]
Products currently stocked:
{'Air Jordan': 2200, 'Cortez': 450, 'Zoom Kobe': 300}
sold: 0
xxxxxxxxxxxxxx6xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxx7xxxxxxxxxxxxxxxx
Branches Opened:[]
Products currently stocked:
{'Air Jordan': 920, 'Cortez': 360, 'Zoom Kobe': 230}
sold: 1440

In [ ]:
class Student:
    ID=0
    def __init__(self,name,dept,age,cgpa):
        self.name=name
        self.dept=dept
        self.age=age
        self.cgpa=cgpa
        Student.ID+=1

    def get_details(self):
        print('ID:',Student.ID)
        print('Name:',self.name)
        print('Department:',self.dept)
        print('Age:',self.age)
        print('CGPA:',self.cgpa)
    @classmethod
    def from_String(cls,info):
        name,dept,age,cg=info.split('-')
        obj=cls(name,dept,age,cg)
        return obj
s1 = Student("Samin", "CSE", 21, 3.91)
s1.get_details()
print("-----------------------")
s2 = Student("Fahim", "ECE", 21, 3.85)
s2.get_details()
print("-----------------------")
s3 = Student("Tahura", "EEE", 22, 3.01)
s3.get_details()
print("-----------------------")
s4 = Student.from_String("Sumaiya-BBA-23-3.96")
s4.get_details()

ID: 1
Name: Samin
Department: CSE
Age: 21
CGPA: 3.91
-----------------------
ID: 2
Name: Fahim
Department: ECE
Age: 21
CGPA: 3.85
-----------------------
ID: 3
Name: Tahura
Department: EEE
Age: 22
CGPA: 3.01
-----------------------
ID: 4
Name: Sumaiya
Department: BBA
Age: 23
CGPA: 3.96

In [ ]:
class Assassin:
    assasin=0

    def __init__(self,name,success):
        self.name=name
        self.success=success
        Assassin.assasin+=1
    def printDetails(self):
        print('Name:',self.name)
        print('Success:',self.success)
        print('Assassin:',Assassin.assasin)
    @classmethod
    def failureRate(cls,name,failure):
        obj=Assassin(name,(100-int(failure)))
        return obj

    @classmethod
    def failurePercentage(cls, name, percentage):
        success = 100 - percentage
        return cls(name, success)

john_wick = Assassin("John Wick", 100)
john_wick.printDetails()
print("================================")
nagisa = Assassin.failureRate("Nagisa", 20)
nagisa.printDetails()
print("================================")
akabane = Assassin.failurePercentage("Akabane", 10)
akabane.printDetails()

Name: John Wick
Success: 100
Assassin: 1
================================
Name: Nagisa
Success: 80
Assassin: 2
================================
Name: Akabane
Success: 90
Assassin: 3

In [ ]:
class Passenger:
    count=0

    def __init__(self,name):
        self.name=name
        Passenger.count+=1
        self.fare=450

    def set_bag_weight(self,w):
        if w<=20:
            self.fare=450
        elif w>=21 and w<=50:
            self.fare+=50
        elif w>50:
            self.fare+=100

    def printDetail(self):
        print(f'Name: {self.name}')
        print(f'Bus fare: {self.fare}')

print("Total Passenger:", Passenger.count)
p1 = Passenger("Jack")
p1.set_bag_weight(90)
p2 = Passenger("Carol")
p2.set_bag_weight(10)
p3 = Passenger("Mike")
p3.set_bag_weight(25)
print("=========================")
p1.printDetail()
print("=========================")
p2.printDetail()
print("=========================")
p3.printDetail()
print("=========================")
print("Total Passenger:", Passenger.count)

Total Passenger: 0
=========================
Name: Jack
Bus fare: 550
=========================
Name: Carol
Bus fare: 450
=========================
Name: Mike
Bus fare: 500
=========================
Total Passenger: 3

In [ ]:
class Travel:
    count=0
    def __init__(self,s,d):
        self.s=s
        self.d=d
        self.time = 1
        Travel.count+=1

    def set_time(self,t):
        self.time=t

    def set_source(self, source):
        self.s = source

    def set_destination(self, destination):
        self.d = destination

    def display_travel_info(self):
         info = f"Source: {self.s}\nDestination: {self.d}\nFlight Time: {self.time}:00"
         return info
print("No. of Traveller =", Travel.count)
print("=======================")
t1 = Travel("Dhaka","India")
print(t1.display_travel_info())
print("=======================")
t2 = Travel("Kuala Lampur","Dhaka")
t2.set_time(23)
print(t2.display_travel_info())
print("=======================")
t3 = Travel("Dhaka","New_Zealand")
t3.set_time(15)
t3.set_destination("Germany")
print(t3.display_travel_info())
print("=======================")
t4 = Travel("Dhaka","India")
t4.set_time(9)
t4.set_source("Malaysia")
t4.set_destination("Canada")
print(t4.display_travel_info())
print("=======================")
print("No. of Traveller =", Travel.count)

No. of Traveller = 0
=======================
Source: Dhaka
Destination: India
Flight Time: 1:00
=======================
Source: Kuala Lampur
Destination: Dhaka
Flight Time: 23:00
=======================
Source: Dhaka
Destination: Germany
Flight Time: 15:00
=======================
Source: Malaysia
Destination: Canada
Flight Time: 9:00
=======================
No. of Traveller = 4

In [ ]:
class Student:
    total_students = 0
    brac_students = 0
    other_students = 0

    def __init__(self, name, department, institution="BRAC University"):
        self.name = name
        self.department = department
        self.institution = institution
        Student.total_students+=1
        if institution == "BRAC University":
            Student.brac_students += 1
        else:
            Student.other_students += 1



    def individualDetail(self):
        print("Name:", self.name)
        print("Department:", self.department)
        print("Institution:", self.institution)


    @classmethod
    def createStudent(cls, name, department, institution="BRAC University"):
        student = cls(name, department, institution)
        return student

    @classmethod
    def printDetails(cls):
        print("Total Student(s):", cls.total_students)
        print("BRAC University Student(s):", cls.brac_students)
        print("Other Institution Student(s):", cls.other_students)

Student.printDetails()
print('#########################')

mikasa = Student('Mikasa Ackerman', "CSE")
mikasa.individualDetail()
print('------------------------------------------')
Student.printDetails()

print('========================')

harry = Student.createStudent('Harry Potter', "Defence Against Dark Arts", "Hogwarts School")
harry.individualDetail()
print('-------------------------------------------')
Student.printDetails()

print('=========================')

levi = Student.createStudent("Levi Ackerman", "CSE")
levi.individualDetail()
print('--------------------------------------------')
Student.printDetails()

Total Student(s): 0
BRAC University Student(s): 0
Other Institution Student(s): 0
#########################
Name: Mikasa Ackerman
Department: CSE
Institution: BRAC University
------------------------------------------
Total Student(s): 1
BRAC University Student(s): 1
Other Institution Student(s): 0
========================
Name: Harry Potter
Department: Defence Against Dark Arts
Institution: Hogwarts School
-------------------------------------------
Total Student(s): 2
BRAC University Student(s): 1
Other Institution Student(s): 1
=========================
Name: Levi Ackerman
Department: CSE
Institution: BRAC University
--------------------------------------------
Total Student(s): 3
BRAC University Student(s): 2
Other Institution Student(s): 1

In [ ]:
class SultansDine:

    total_branch = 0
    total_sell = 0
    branch_info = []

    def __init__(self, branch):
        self.name = branch
        SultansDine.total_branch += 1

    def sellQuantity(self, quantity):

        if quantity < 10:
            self.branch_sell = quantity * 300
        elif quantity < 20:
            self.branch_sell = quantity * 350
        else:
            self.branch_sell = quantity * 400

        SultansDine.total_sell += self.branch_sell
        SultansDine.branch_info.append(self.name)
        SultansDine.branch_info.append(self.branch_sell)

    def branchInformation(self):
        print(f"Branch Name: {self.name}")
        print(f"Branch Sell: {self.branch_sell}")

    @classmethod
    def details(cls):
        print(f"Total Number of branch(s): {cls.total_branch}")
        print(f"Total Sell: {cls.total_sell}")

        for i in range(0, len(SultansDine.branch_info), 2):
            print(
                f"Branch Name: {SultansDine.branch_info[i]}, Branch Sell: {SultansDine.branch_info[i + 1]} Taka"
            )
            print(
                f"Branch consists of total sell's: {(SultansDine.branch_info[i + 1] / SultansDine.total_sell) * 100:.2f}%"
            )


SultansDine.details()
print('########################')
dhanmondi = SultansDine('Dhanmondi')
dhanmondi.sellQuantity(25)
dhanmondi.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

baily_road = SultansDine('Baily Road')
baily_road.sellQuantity(15)
baily_road.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

gulshan = SultansDine('Gulshan')
gulshan.sellQuantity(9)
gulshan.branchInformation()
print('-----------------------------------------')
SultansDine.details()

Total Number of branch(s): 0
Total Sell: 0
########################
Branch Name: Dhanmondi
Branch Sell: 10000
-----------------------------------------
Total Number of branch(s): 1
Total Sell: 10000
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 100.00%
========================
Branch Name: Baily Road
Branch Sell: 5250
-----------------------------------------
Total Number of branch(s): 2
Total Sell: 15250
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 65.57%
Branch Name: Baily Road, Branch Sell: 5250 Taka
Branch consists of total sell's: 34.43%
========================
Branch Name: Gulshan
Branch Sell: 2700
-----------------------------------------
Total Number of branch(s): 3
Total Sell: 17950
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 55.71%
Branch Name: Baily Road, Branch Sell: 5250 Taka
Branch consists of total sell's: 29.25%
Branch Name: Gulshan, Branch Sell: 2700 Taka
Branch consists of total sell's: 15.04%

In [ ]:
class Puzzle:
    x = 0
    def methodA(self):
        Puzzle.x = 5
        z = Puzzle.x + self.methodB(Puzzle.x)
        print(Puzzle.x, z)
        z = self.methodB(z + 2) + Puzzle.x
        print(Puzzle.x, z)
        self.methodB(Puzzle.x, z)
        print(Puzzle.x, z)
    def methodB(self, *args):
        if len(args) == 1:
            y = args[0]
            Puzzle.x = y + Puzzle.x
            print(Puzzle.x, y)
            return Puzzle.x + 3
        else:
            z, x = args
            z = z + 1
            x = x + 1
            print(z, x)

p = Puzzle()
p.methodA()
p.methodA()
p = Puzzle()
p.methodA()
p.methodB(7)

10 5
10 18
30 20
30 63
31 64
30 63
10 5
10 18
30 20
30 63
31 64
30 63
10 5
10 18
30 20
30 63
31 64
30 63
37 7

40

In [ ]:
class FinalT6A:
    temp = 3
    def __init__(self, x, p):
        self.sum, self.y = 0, 2
        FinalT6A.temp += 3
        self.y = self.temp - p
        self.sum = self.temp + x
        print(x, self.y, self.sum)
    def methodA(self):
        x, y = 0, 0
        y = y + self.y
        x = self.y + 2 + self.temp
        self.sum = x + y + self.methodB(self.temp, y)
        print(x, y, self.sum)
    def methodB(self, temp, n):
        x = 0
        FinalT6A.temp += 1
        self.y = self.y + (FinalT6A.temp)
        FinalT6A.temp -= 1
        x = x + 2 + n
        self.sum = self.sum + x + self.y
        print(x, self.y, self.sum)
        return self.sum
q1 = FinalT6A(2,1)
q1.methodA()
q1.methodA()

2 5 8
7 12 27
13 5 45
14 19 78
20 12 110

In [ ]:
class SultansDine:
    l=[]
    total_branch=0
    totalsell=0
    def __init__(self,location):
        self.__location=location
        self.__b_sell=0
        SultansDine.total_branch+=1


    def sellQuantity(self,q):
        if q<10:
            self.__b_sell=int(q*300)
        elif q<20:
            self.__b_sell=int(q*350)
        else:
            self.__b_sell=int(q*400)
        SultansDine.totalsell+=self.__b_sell
        SultansDine.l.append(self.__location)
        SultansDine.l.append(self.__b_sell)


    def branchInformation(self):
        print(f'Branch Name: {self.__location}')
        print(f'Branch Sell: {self.__b_sell}')
    @classmethod
    def details(cls):
        print(f'Total Number of branches{len(SultansDine.l)}')
        print(f'Total Sell:{SultansDine.totalsell}')
        for i in range(0,len(SultansDine.l)-1,2):
            print(f'Branch Name{SultansDine.l[i]}, Branch Sell {SultansDine.l[i+1]}')
            print(f'Branch Consists of total sell : {(SultansDine.l[i+1]/ SultansDine.totalsell)*100:.2f}%')

SultansDine.details()
print('########################')
dhanmondi = SultansDine('Dhanmondi')
dhanmondi.sellQuantity(25)
dhanmondi.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

baily_road = SultansDine('Baily Road')
baily_road.sellQuantity(15)
baily_road.branchInformation()
print('-----------------------------------------')
SultansDine.details()

print('========================')

gulshan = SultansDine('Gulshan')
gulshan.sellQuantity(9)
gulshan.branchInformation()
print('-----------------------------------------')
SultansDine.details()

Total Number of branches0
Total Sell:0
########################
Branch Name: Dhanmondi
Branch Sell: 10000
-----------------------------------------
Total Number of branches2
Total Sell:10000
Branch NameDhanmondi, Branch Sell 10000
Branch Consists of total sell : 100.00%
========================
Branch Name: Baily Road
Branch Sell: 5250
-----------------------------------------
Total Number of branches4
Total Sell:15250
Branch NameDhanmondi, Branch Sell 10000
Branch Consists of total sell : 65.57%
Branch NameBaily Road, Branch Sell 5250
Branch Consists of total sell : 34.43%
========================
Branch Name: Gulshan
Branch Sell: 2700
-----------------------------------------
Total Number of branches6
Total Sell:17950
Branch NameDhanmondi, Branch Sell 10000
Branch Consists of total sell : 55.71%
Branch NameBaily Road, Branch Sell 5250
Branch Consists of total sell : 29.25%
Branch NameGulshan, Branch Sell 2700
Branch Consists of total sell : 15.04%

In [ ]:
class Assassin:
    total=0
    def __init__(self,n,s):
        self.n=n
        self.s=s

        Assassin.total+=1
    def printDetails(self):
        print('Name:',self.n)
        print('Success Rate:',self.s)
        print('Total Number of Assassin',Assassin.total)
    @classmethod
    def failurePercentage(cls,n1,f):
        f=int(f[0:-1])
        obj=cls(n1,(100-f))
        return obj
    @classmethod
    def failureRate(cls,n1,f):
        obj=cls(n1,(100-f))
        return obj


john_wick = Assassin('John Wick', 100)
john_wick.printDetails()
print('================================')
nagisa = Assassin.failureRate("Nagisa", 20)
nagisa.printDetails()
print('================================')
akabane = Assassin.failurePercentage("Akabane", "10%")
akabane.printDetails()

Name: John Wick
Success Rate: 100
Total Number of Assassin 1
================================
Name: Nagisa
Success Rate: 80
Total Number of Assassin 2
================================
Name: Akabane
Success Rate: 90
Total Number of Assassin 3

In [ ]:
class Student:
    def __init__(self, name='Just a student', dept='nothing'):
        self.__name = name
        self.__department = dept
    def set_department(self, dept):
        self.__department = dept
    def get_name(self):
        return self.__name
    def set_name(self,name):
        self.__name = name
    def detail(self):
        return 'Name: '+self.__name+' Department: '+self.__department

class BBA_Student(Student):
    def __init__(self, name='Default'):
        super().__init__(name, 'BBA')


#write your code here

print(BBA_Student().detail())
print(BBA_Student('Humpty Dumpty').detail())
print(BBA_Student('Little Bo Peep').detail())

Name: Default Department: BBA
Name: Humpty Dumpty Department: BBA
Name: Little Bo Peep Department: BBA

In [ ]:
class Vehicle:
    def __init__(self):
        self.x = 0
        self.y = 0
    def moveUp(self):
        self.y += 1
    def moveDown(self):
        self.y -= 1
    def moveRight(self):
        self.x += 1
    def moveLeft(self):
        self.x -= 1
    def detail(self):
        return '('+str(self.x)+' , '+str(self.y)+')'

class Vehicle2010(Vehicle):

    def moveLowerLeft(self):
        self.x -= 1
        self.y -= 1

    def equals(self,c2):
        return self.detail() == c2.detail()


#write your code here

print('Part 1')
print('------')
car = Vehicle()
print(car.detail())
car.moveUp()
print(car.detail())
car.moveLeft()
print(car.detail())
car.moveDown()
print(car.detail())
car.moveRight()
print(car.detail())
print('------')
print('Part 2')
print('------')
car1 = Vehicle2010()
print(car1.detail())
car1.moveLowerLeft()
print(car1.detail())
car2 = Vehicle2010()
car2.moveLeft()
print(car1.equals(car2))
car2.moveDown()
print(car1.equals(car2))

Part 1
------
(0 , 0)
(0 , 1)
(-1 , 1)
(-1 , 0)
(0 , 0)
------
Part 2
------
(0 , 0)
(-1 , -1)
False
True

In [ ]:
class Tournament:
    def __init__(self, name='Default'):
        self.__name = name

    def set_name(self, name):
        self.__name = name

    def get_name(self):
        return self.__name

class Cricket_Tournament(Tournament):
    def __init__(self, name='Default', teams=0, format_='No type'):
        super().__init__(name)
        self.teams = teams
        self.format_ = format_

    def detail(self):
        return f"Cricket Tournament Name: {self.get_name()} Number of Teams: {self.teams} Type: {self.format_}"

class Tennis_Tournament(Tournament):
    def __init__(self, name='Default', players=0):
        super().__init__(name)
        self.players = players

    def detail(self):
        return f"Tennis Tournament Name: {self.get_name()} Number of Players: {self.players}"

# Test cases
ct1 = Cricket_Tournament()
print(ct1.detail())
print("-----------------------")
ct2 = Cricket_Tournament("IPL", 10, "t20")
print(ct2.detail())
print("-----------------------")
tt = Tennis_Tournament("Roland Garros", 128)
print(tt.detail())

Cricket Tournament Name: Default Number of Teams: 0 Type: No type
-----------------------
Cricket Tournament Name: IPL Number of Teams: 10 Type: t20
-----------------------
Tennis Tournament Name: Roland Garros Number of Players: 128

In [ ]:
class Product:
    def __init__(self, id, title, price):
        self.__id = id
        self.__title = title
        self.__price = price

    def get_id_title_price(self):
        return f"ID: {self.__id} Title: {self.__title} Price: {self.__price}"

class Book(Product):
    def __init__(self, id, title, price, isbn, publisher):
        super().__init__(id, title, price)
        self.isbn = isbn
        self.publisher = publisher

    def printDetail(self):
        return f"{self.get_id_title_price()} ISBN: {self.isbn} Publisher: {self.publisher}"

class CD(Product):
    def __init__(self, id, title, price, band, duration, genre):
        super().__init__(id, title, price)
        self.band = band
        self.duration = duration
        self.genre = genre

    def printDetail(self):
        return f"{self.get_id_title_price()} Band: {self.band} Duration: {self.duration} minutes Genre: {self.genre}"

# Test cases
book = Book(1, "The Alchemist", 500, "97806", "HarperCollins")
print(book.printDetail())
print("-----------------------")
cd = CD(2, "Shotto", 300, "Warfaze", 50, "Hard Rock")
print(cd.printDetail())

ID: 1 Title: The Alchemist Price: 500 ISBN: 97806 Publisher: HarperCollins
-----------------------
ID: 2 Title: Shotto Price: 300 Band: Warfaze Duration: 50 minutes Genre: Hard Rock

In [ ]:
class Fruit:
    def __init__(self, formalin=False, name=''):
        self.__formalin = formalin
        self.name = name

    def getName(self):
        return self.name

    def hasFormalin(self):
        return self.__formalin




class Mango(Fruit):
    def __init__(self):
        super().__init__(True,'Mango')
    def __str__(self):
        return "Mangoes are bad for you"

class Jackfruit(Fruit):
    def __init__(self):
        super().__init__(False, 'Jackfruit')
    def __str__(self):
         return "Jackfruits are good for you"

class testFruit:
    def test(self, f):
        print('----Printing Detail----')
        if f.hasFormalin():
            print(f'Do not eat the {f.getName()}.')
            print(f)
        else:
            print(f'Eat the {f.getName()}.')
            print(f)

m = Mango()
j = Jackfruit()
t1 = testFruit()
t1.test(m)
t1.test(j)

----Printing Detail----
Do not eat the Mango.
Mangoes are bad for you
----Printing Detail----
Eat the Jackfruit.
Jackfruits are good for you

![download.png]()

In [ ]:
class PokemonBasic:

    def __init__(self, name='Default', hp=0, weakness='None', type='Unknown'):
        self.name = name
        self.hit_point = hp
        self.weakness = weakness
        self.main_type = type

    def get_type(self):
        return 'Main type: ' + self.main_type

    def get_move(self):
        return 'Basic move: ' + 'Quick Attack'

    def __str__(self):
        return "Name: " + self.name + ", HP: " + str(self.hit_point) + ", Weakness: " + self.weakness

class PokemonExtra (PokemonBasic):
    def __init__(self,name,hp,weakness,main_type,second_type=None,other=None):
        super().__init__(name,hp,weakness,main_type)
        self.second_type=second_type
        if other:
            self.other=other
        else:
            self.other=[]

    def get_type(self):
        if self.second_type:
            return f"Main type: {self.main_type} , secondary type: {self.second_type}"
        else:
            return f'Main type : {self.main_type}'

    def get_move(self):
        basic=super().get_move()
        if  self.other:
            x=', '.join(self.other)
            return f"{basic} \nOther Move: {x}"
        else:
            return  f"{basic}"


print('\n------------Basic Info:--------------')
pk = PokemonBasic()
print(pk)
print(pk.get_type())
print(pk.get_move())

print('\n------------Pokemon 1 Info:-------------')
charmander = PokemonExtra('Charmander', 39, 'Water', 'Fire')
print(charmander)
print(charmander.get_type())
print(charmander.get_move())

print('\n------------Pokemon 2 Info:-------------')
charizard = PokemonExtra('Charizard', 78, 'Water', 'Fire', 'Flying', ['Fire Spin', 'Fire Blaze'])
print(charizard)
print(charizard.get_type())
print(charizard.get_move())

------------Basic Info:--------------
Name: Default, HP: 0, Weakness: None
Main type: Unknown
Basic move: Quick Attack

------------Pokemon 1 Info:-------------
Name: Charmander, HP: 39, Weakness: Water
Main type : Fire
Basic move: Quick Attack

------------Pokemon 2 Info:-------------
Name: Charizard, HP: 78, Weakness: Water
Main type: Fire , secondary type: Flying
Basic move: Quick Attack
Other Move: Fire Spin, Fire Blaze

In [ ]:
class Robot:
    robots = {}
    robot_num = 0

    def __init__(self, name, rID):
        self.__name = name
        self.__rID = rID

    def setRID(self, rID):
        self.__rID = rID

    def getRID(self):
        return self.__rID
    def getname(self):
        return self.__name
    def __str__(self):
        return f'Name: {self.__name}\nRobot ID: {self.__rID}'

class HumanoidRobot(Robot):
    def __init__(self, name, rID, robot_type, manufacturer, *functions):
        super().__init__(name, rID)
        self.robot_type = robot_type
        self.manufacturer = manufacturer
        self.functions=list(functions)
        Robot.robot_num += 1
        self.robot_id_str = f'{Robot.robot_num}_{rID}_{name[0]}'
    def addFunctions(self,*F):
         self.functions.extend(F)
    def makeRobotCode(self):
         x=super().getname()
         print("A Code has been created and saved for your Robot!")
         Robot.robots[ self.robot_id_str]=x
    def __str__(self):
        return f'{super().__str__()}\nRobot Type: {self.robot_type}\nManufacturer: {self.manufacturer}\nFunctions: {self.functions}'

    @classmethod
    def makeRobot(cls, name, rID, robot_type, manufacturer, *functions):
        robot = cls(name, rID, robot_type, manufacturer, *functions)
        return robot

print(f'All robots Info:\n{Robot.robots}')
robot1 = HumanoidRobot('Sophia', 1010, "Humanoid", 'Hanson Electronics', 'Face recognition', 'NLP')
print('1================================')
robot1.makeRobotCode()
print('2================================')
robot1.addFunctions('Speech Recognition')
print(robot1)
print('3================================')
print(f'All robots Info:\n{Robot.robots}')
robot2 = HumanoidRobot.makeRobot('Ultron', 320, "Humanoid", 'Stark Industries', 'Face recognition', 'NLP', 'Flight Power')
print('4================================')
robot2.makeRobotCode()
print('5================================')
robot2.addFunctions('SuperHuman Durability')
print(robot2)
print('6================================')
print(f'All robots Info:\n{Robot.robots}')
print('Total robots:', Robot.robot_num)

All robots Info:
{}
1================================
A Code has been created and saved for your Robot!
2================================
Name: Sophia
Robot ID: 1010
Robot Type: Humanoid
Manufacturer: Hanson Electronics
Functions: ['Face recognition', 'NLP', 'Speech Recognition']
3================================
All robots Info:
{'1_1010_S': 'Sophia'}
4================================
A Code has been created and saved for your Robot!
5================================
Name: Ultron
Robot ID: 320
Robot Type: Humanoid
Manufacturer: Stark Industries
Functions: ['Face recognition', 'NLP', 'Flight Power', 'SuperHuman Durability']
6================================
All robots Info:
{'1_1010_S': 'Sophia', '2_320_U': 'Ultron'}
Total robots: 2

In [ ]:
class Shape:

  def __init__(self, name='Default', height=0, base=0):
    self.area = 0
    self.name = name
    self.height = height
    self.base = base

  def get_height_base(self):
    return "Height: "+str(self.height)+", Base: "+str(self.base)

class triangle (Shape):
    def __init__(self,name='Default',height=0,base=0):
        super().__init__(name,height,base)
    def calcArea(self):
        self.area=(0.5)*(self.height)*(self.base)
    def printDetail(self):
        x = super().get_height_base()
        y = f"Shape name: {self.name}\n{x}, Area: {float(self.area)}"
        return y

class trapezoid(Shape):
  def __init__(self,name,height,base,side):
     super().__init__(name,height,base)
     self.side = side

  def calcArea(self):
    self.area = 0.5*self.height*(self.base+self.side)

  def printDetail(self):
        x = super().get_height_base()
        y = f"Shape name: {self.name}\n{x}, Side_A: {self.side}, Area: {float(self.area)}"
        return y

tri_default = triangle()
tri_default.calcArea()
print(tri_default.printDetail())
print('--------------------------')
tri = triangle('Triangle', 10, 5)
tri.calcArea()
print(tri.printDetail())
print('---------------------------')
trap = trapezoid('Trapezoid', 10, 6, 4)
trap.calcArea()
print(trap.printDetail())

Shape name: Default
Height: 0, Base: 0, Area: 0.0
--------------------------
Shape name: Triangle
Height: 10, Base: 5, Area: 25.0
---------------------------
Shape name: Trapezoid
Height: 10, Base: 6, Side_A: 4, Area: 50.0

In [ ]:
class SportsPerson:

  def __init__(self, team_name, name, role):
    self.__team = team_name
    self.__name = name
    self.role = role
    self.earning_per_match = 0

  def get_name_team(self):
    return 'Name: '+self.__name+', Team Name: ' +self.__team


class Player(SportsPerson):
  def __init__(self,name1,name,role,gol,pla):
    super().__init__(name1,name,role)
    self.goals = gol
    self.played = pla
    self.earning_per_match = (self.goals*1000)+(self.played*10)

  def calculate_ratio(self):
    self.ratio = self.goals/self.played

  def print_details(self):
    x=super().get_name_team()
    print(x)
    print(f"Team Role: {self.role}")
    print(f"Total Goal: {self.goals}, Total Played: {self.played}")
    print(f"Goal Ratio: {self.ratio}")
    print(f"Match Earning: {self.earning_per_match}k")

class Manager(SportsPerson):
  def __init__(self,nam1,nam,rol,win):
    super().__init__(nam1,nam,rol)
    self.win = win
    self.earning_per_match = self.win*1000

  def print_details(self):
    x=super().get_name_team()
    print(x)
    print(f"Team Role: {self.role}")
    print(f"Total Win: {self.win}")
    print(f"Match Earning: {self.earning_per_match}k")

player_one = Player('Al-Nassr', 'Ronaldo', 'Striker', 25, 32)
player_one.calculate_ratio()
player_one.print_details()
print('------------------------------------------')
manager_one = Manager('Real Madrid', 'Zidane', 'Manager', 25)
manager_one.print_details()

Name: Ronaldo, Team Name: Al-Nassr
Team Role: Striker
Total Goal: 25, Total Played: 32
Goal Ratio: 0.78125
Match Earning: 25320k
------------------------------------------
Name: Zidane, Team Name: Real Madrid
Team Role: Manager
Total Win: 25
Match Earning: 25000k

In [ ]:
class KK_tea:
  dic = {}
  count = 0
  status = False

  def __init__(self,pri,bags=50):
    self.price = pri
    self.bags = bags
    self.name = 'KK Regular Tea'
    KK_tea.dic[self.name] = KK_tea.count

  def product_detail(self):
    rock = self.bags*2
    print(f"Name: {self.name}, Weight: {rock}")
    print(f"Tea Bags: {self.bags}, Price: {self.price}")
    print(f"Status: {KK_tea.status} ")
    KK_tea.status = False

  @classmethod
  def update_sold_status_regular(cls,*args):
    cls.count = len(args)
    for i in args:
        cls.status = True
        cls.dic[i.name] = cls.count

  @classmethod
  def total_sales(cls):
    print(f"Total sales: {cls.dic}")




class KK_flavoured_tea(KK_tea):
  def __init__(self,name,price,bags):
    super().__init__(price,bags)
    self.name = name
    buki = 'KK '+self.name+' Tea'
    self.name = buki

  @classmethod
  def update_sold_status_flavoured(cls,*dop):
    for i in dop:
      cls.status = True
      if i.name in cls.dic:
        cls.dic[i.name] += 1
      else:
         cls.dic[i.name]=1


t1 = KK_tea(250)
print("-----------------1-----------------")
t1.product_detail()
print("-----------------2-----------------")
KK_tea.total_sales()
print("-----------------3-----------------")
t2 = KK_tea(470, 100)
t3 = KK_tea(360, 75)
KK_tea.update_sold_status_regular(t1, t2, t3)
print("-----------------4-----------------")
t3.product_detail()
print("-----------------5-----------------")
KK_tea.total_sales()
print("-----------------6-----------------")
t4 = KK_flavoured_tea("Jasmine", 260, 50)
t5 = KK_flavoured_tea("Honey Lemon", 270, 45)
t6 = KK_flavoured_tea("Honey Lemon", 270, 45)
print("-----------------7-----------------")
t4.product_detail()
print("-----------------8-----------------")
t6.product_detail()
print("-----------------9-----------------")
KK_flavoured_tea.update_sold_status_flavoured(t4, t5, t6)
print("-----------------10-----------------")
KK_tea.total_sales()

-----------------1-----------------
Name: KK Regular Tea, Weight: 100
Tea Bags: 50, Price: 250
Status: False
-----------------2-----------------
Total sales: {'KK Regular Tea': 0}
-----------------3-----------------
-----------------4-----------------
Name: KK Regular Tea, Weight: 150
Tea Bags: 75, Price: 360
Status: True
-----------------5-----------------
Total sales: {'KK Regular Tea': 3}
-----------------6-----------------
-----------------7-----------------
Name: KK Jasmine Tea, Weight: 100
Tea Bags: 50, Price: 260
Status: False
-----------------8-----------------
Name: KK Honey Lemon Tea, Weight: 90
Tea Bags: 45, Price: 270
Status: False
-----------------9-----------------
-----------------10-----------------
Total sales: {'KK Regular Tea': 3, 'KK Jasmine Tea': 1, 'KK Honey Lemon Tea': 2}

In [ ]:
class KK_tea:
    total={}
    count=0
    def __init__(self,price,bags=50):
        self.name='KK Regular Tea'
        self.weight=0
        self.price=price
        self.bags=bags
        self.status=False
        KK_tea.total[self.name] = KK_tea.count

    @classmethod
    def total_sales(cls):
        print(f'Total sales: {cls.total}')
    @classmethod
    def update_sold_status_regular(cls,*t):
        for i in t:
            cls.count+=1
            i.status=True
            cls.total[i.name]=cls.count
    def product_detail(self):
        self.weight = self.bags*2
        print(f'Name: {self.name}')
        print(f'Tea bags: {self.bags}')
        print(f'price: {self.price}')
        print(f'Status: {self.status}')

class KK_flavoured_tea(KK_tea):
     def __init__(self,name,price,bags):
        super().__init__(price,bags)
        self.name = name
        buki = 'KK '+self.name+' Tea'
        self.name = buki
        self.status=False

     @classmethod
     def update_sold_status_flavoured(cls,*t):
        for i in t:
            i.status=True
            if i.name in cls.total:
                cls.total[i.name] += 1
            else:
                cls.total[i.name]=1
t1 = KK_tea(250)
print("-----------------1-----------------")
t1.product_detail()
print("-----------------2-----------------")
KK_tea.total_sales()
print("-----------------3-----------------")
t2 = KK_tea(470, 100)
t3 = KK_tea(360, 75)
KK_tea.update_sold_status_regular(t1, t2, t3)
print("-----------------4-----------------")
t3.product_detail()
print("-----------------5-----------------")
KK_tea.total_sales()
print("-----------------6-----------------")
t4 = KK_flavoured_tea("Jasmine", 260, 50)
t5 = KK_flavoured_tea("Honey Lemon", 270, 45)
t6 = KK_flavoured_tea("Honey Lemon", 270, 45)
print("-----------------7-----------------")
t4.product_detail()
print("-----------------8-----------------")
t6.product_detail()
print("-----------------9-----------------")
KK_flavoured_tea.update_sold_status_flavoured(t4, t5, t6)
print("-----------------10-----------------")
KK_tea.total_sales()

-----------------1-----------------
Name: KK Regular Tea
Tea bags: 50
price: 250
Status: False
-----------------2-----------------
Total sales: {'KK Regular Tea': 0}
-----------------3-----------------
-----------------4-----------------
Name: KK Regular Tea
Tea bags: 75
price: 360
Status: True
-----------------5-----------------
Total sales: {'KK Regular Tea': 3}
-----------------6-----------------
-----------------7-----------------
Name: KK Jasmine Tea
Tea bags: 50
price: 260
Status: False
-----------------8-----------------
Name: KK Honey Lemon Tea
Tea bags: 45
price: 270
Status: False
-----------------9-----------------
-----------------10-----------------
Total sales: {'KK Regular Tea': 3, 'KK Jasmine Tea': 1, 'KK Honey Lemon Tea': 2}

In [ ]:
import math

class Point:

  def __init__(self, x=0, y=0):
    self.x = x
    self.y = y
    self.area = 0


  def calculate_area(self):
    return self.area


  def print_details(self):
    print("--------- Printing details ----------")
    print(f'Co-ordinate: ({self.x},{self.y})')
    print(f'Area: {self.area}')


class Circle(Point):
    def __init__(self,radius=1, x=0, y=0):
        super().__init__(x, y)
        self.radius = radius
        self.area = math.pi * (radius ** 2)

    def calculate_area(self):
        return self.area

    def print_details(self):
        print("--------- Printing details ----------")
        print(f'Co-ordinate: ({self.x},{self.y})')
        print(f'Area: {self.area}')
        print(f'Radius: {self.radius}')

class Sphere(Circle):
    def __init__(self,radius=1, x=0, y=0):
        super().__init__(x, y)
        self.radius = radius
        x=super().calculate_area()
        self.area = 4 * x

    def calculate_area(self):
        return self.area

    def print_details(self):
        print("--------- Printing details ----------")
        print(f'Co-ordinate: ({self.x},{self.y})')
        print(f'Area: {self.area}')
        print(f'Radius: {self.radius}')

print("--------------1---------------")
p1 = Point(2,3)
print(f'Area of p1: {p1.calculate_area()}')
print("--------------2---------------")
p1.print_details()
print("--------------3---------------")
p2 = Point()
p2.print_details()
print("--------------4---------------")
c1 = Circle(4,0,3)
print(f'Area of c1: {c1.calculate_area()}')
print("--------------5---------------")
c1.print_details()
print("--------------6---------------")
c2 = Circle(7)
print(f'Area of c2: {c2.calculate_area()}')
print("--------------7---------------")
sph1 = Sphere(3,0,2)
print(f'Area of sph1: {sph1.calculate_area()}')
print("--------------8---------------")
sph1.print_details()
print("--------------9---------------")
sph2 = Sphere(6)
print(f'Area of sph2: {sph2.calculate_area()}')

--------------1---------------
Area of p1: 0
--------------2---------------
--------- Printing details ----------
Co-ordinate: (2,3)
Area: 0
--------------3---------------
--------- Printing details ----------
Co-ordinate: (0,0)
Area: 0
--------------4---------------
Area of c1: 50.26548245743669
--------------5---------------
--------- Printing details ----------
Co-ordinate: (0,3)
Area: 50.26548245743669
Radius: 4
--------------6---------------
Area of c2: 153.93804002589985
--------------7---------------
Area of sph1: 0.0
--------------8---------------
--------- Printing details ----------
Co-ordinate: (2,0)
Area: 0.0
Radius: 3
--------------9---------------
Area of sph2: 0.0

![Screenshot (217).png]()

In [ ]:
class Account:
    def __init__(self, account_number, balance):
        self.account_number = account_number
        self.balance = balance
        self.account_type = "General"
        self.maturity = 0

    def print_details(self):
        print("------ Account details ------")
        print(f"Account Type: {self.account_type}, Maturity: {self.maturity} years")
        print(f"Account Number: {self.account_number}, Balance: ${self.balance:.2f}")

    def deposit(self, amount):
        self.balance += amount
        print(f"Deposited ${amount:.2f}. New Balance: ${self.balance:.2f}")

    def withdraw(self, amount):
        if self.balance >= amount:
            self.balance -= amount
            print(f"Withdrew ${amount:.2f}. New Balance: ${self.balance:.2f}")
        else:
            print("Insufficient funds.")

    def year_passed(self, year):
        self.maturity += year
        print(f"Maturity of the account: {self.maturity} years")


class SavingsAccount(Account):
    def __init__(self, account_number, balance, interest_rate, minimum_limit):
        super().__init__(account_number, balance)
        self.account_type = "Savings"
        self.interest_rate = interest_rate
        self.minimum_limit = minimum_limit

    def print_details(self):
        super().print_details()
        print(f'Interest Rate: {self.interest_rate}')
        print(f'Minimum Limit: {self.minimum_limit}')


    def withdraw(self, amount):
        if self.balance >= amount:
            if amount<=self.minimum_limit:
                self.balance -= amount
                print(f"Withdrew ${amount:.2f}. New Balance: ${self.balance:.2f}")
            else:
                print("Insufficient funds.")
        else:
                print("Insufficient funds.")



    def apply_interest(self):
        interest_amount = self.balance * self.interest_rate
        self.balance += interest_amount
        print(f'Interest applied new Balance {self.balance}')


class FixedDepositAccount(Account):
    def __init__(self, account_number, balance, maturity_period):
        super().__init__(account_number, balance)
        self.account_type = "Fixed Deposit"
        self.maturity_period = maturity_period

    def withdraw(self, amount):
        if self.maturity >= self.maturity_period:
            super().withdraw(amount)
        else:
            print("Can not withdraw, Account is not matured")

    def year_passed(self, year):
        super().year_passed(year)

# Driver Code
print("-----------1------------")
account = Account("A203", 2000)
account.print_details()
print("-----------2------------")
account.deposit(400)
account.withdraw(1500)
account.year_passed(2)
print("-----------3------------")
account.print_details()
print("-----------4------------")
savings_account = SavingsAccount("SA123", 1000, 0.05, 800)
savings_account.print_details()
print("-----------5------------")
savings_account.deposit(400)
print("-----------6------------")
savings_account.withdraw(1000)
print("-----------7------------")
savings_account.withdraw(800)
print("-----------8------------")
savings_account.apply_interest()
print("-----------9------------")
savings_account.print_details()
print("-----------10------------")
fixed_account1 = FixedDepositAccount("FDA321", 10000, 5)
fixed_account1.print_details()
print("-----------11------------")
fixed_account1.deposit(400)
print("-----------12------------")
fixed_account1.year_passed(6)
print("-----------13------------")
fixed_account1.withdraw(10000)
print("-----------14------------")
fixed_account1.print_details()
print("-----------15------------")
fixed_account2 = FixedDepositAccount("FDA300", 50000, 7)
fixed_account2.print_details()
print("-----------16------------")
fixed_account2.withdraw(10000)

-----------1------------
------ Account details ------
Account Type: General, Maturity: 0 years
Account Number: A203, Balance: $2000.00
-----------2------------
Deposited $400.00. New Balance: $2400.00
Withdrew $1500.00. New Balance: $900.00
Maturity of the account: 2 years
-----------3------------
------ Account details ------
Account Type: General, Maturity: 2 years
Account Number: A203, Balance: $900.00
-----------4------------
------ Account details ------
Account Type: Savings, Maturity: 0 years
Account Number: SA123, Balance: $1000.00
Interest Rate: 0.05
Minimum Limit: 800
-----------5------------
Deposited $400.00. New Balance: $1400.00
-----------6------------
Insufficient funds.
-----------7------------
Withdrew $800.00. New Balance: $600.00
-----------8------------
Interest applied new Balance 630.0
-----------9------------
------ Account details ------
Account Type: Savings, Maturity: 0 years
Account Number: SA123, Balance: $630.00
Interest Rate: 0.05
Minimum Limit: 800
-----------10------------
------ Account details ------
Account Type: Fixed Deposit, Maturity: 0 years
Account Number: FDA321, Balance: $10000.00
-----------11------------
Deposited $400.00. New Balance: $10400.00
-----------12------------
Maturity of the account: 6 years
-----------13------------
Withdrew $10000.00. New Balance: $400.00
-----------14------------
------ Account details ------
Account Type: Fixed Deposit, Maturity: 6 years
Account Number: FDA321, Balance: $400.00
-----------15------------
------ Account details ------
Account Type: Fixed Deposit, Maturity: 0 years
Account Number: FDA300, Balance: $50000.00
-----------16------------
Can not withdraw, Account is not matured

In [ ]:
# Task - 1

class Employee:

    salary = 30000
    status = "Normal"
    def __init__(self, name, id, dept):
        self.name = name
        self.id = id
        self.dept = dept

    def employeeDetails(self):
        print(f"Name: {self.name}, Dept {self.dept}")
        print(f"Employee id: {self.id}, Salary: {self.salary}")

    def workDistribution(self, new):
        self.dept = new
        if self.dept == "Human Resource":
            print("Collect work distribution details from the manager.")
        else:
            print("Collect work distribution loads from the HR department.")

    def increment(self):
        if self.status == "Normal":
            self.salary += float(self.salary*0.1)
        elif self.status == "Foreign":
            self.salary+= float(self.salary*0.15)
        elif self.status == "Part":
            print("Sadly, there is no increment for the part time")

class Foreign_employee(Employee):
    def __init__(self, name, id, dept):
        super().__init__(name, id, dept)
        Employee.status = "Foreign"
        self.salary = 30000

class Part_time_employee(Employee):
    def __init__(self, name, id, dept):
        super().__init__(name, id, dept)
        Employee.status = "Part"
        self.salary = 15000

print("1------------------------------------------")
emp1=Employee("Nawaz Ali", 102, "Marketing")
print("2------------------------------------------")
emp1.employeeDetails()
print("3------------------------------------------")
emp1.workDistribution("Marketing")
print("4------------------------------------------")
emp1.increment()
emp1.employeeDetails()
print("5------------------------------------------")
f_emp=Foreign_employee("Nadvi", 311, "Human Resource")
f_emp.employeeDetails()
print("6------------------------------------------")
f_emp.workDistribution("Human Resource")
print("7------------------------------------------")
f_emp.increment()
f_emp.employeeDetails()
print("8------------------------------------------")
p1_emp=Part_time_employee("Asif", 210, "Sales")
p2_emp=Part_time_employee("Olive", 223, "Accounts")
print("9------------------------------------------")
p1_emp.employeeDetails()
print("10------------------------------------------")
p1_emp.workDistribution("Sales")
print("11------------------------------------------")
p2_emp.increment()
print("12------------------------------------------")
p2_emp.employeeDetails()

1------------------------------------------
2------------------------------------------
Name: Nawaz Ali, Dept Marketing
Employee id: 102, Salary: 30000
3------------------------------------------
Collect work distribution loads from the HR department.
4------------------------------------------
Name: Nawaz Ali, Dept Marketing
Employee id: 102, Salary: 33000.0
5------------------------------------------
Name: Nadvi, Dept Human Resource
Employee id: 311, Salary: 30000
6------------------------------------------
Collect work distribution details from the manager.
7------------------------------------------
Name: Nadvi, Dept Human Resource
Employee id: 311, Salary: 34500.0
8------------------------------------------
9------------------------------------------
Name: Asif, Dept Sales
Employee id: 210, Salary: 15000
10------------------------------------------
Collect work distribution loads from the HR department.
11------------------------------------------
Sadly, there is no increment for the part time
12------------------------------------------
Name: Olive, Dept Accounts
Employee id: 223, Salary: 15000

In [ ]:
class Employee:

    def __init__(self,name,id,dept):
        self.name=name
        self.id=id
        self.dept=dept
        self.salary=30000
        self.status='Normal'
    def workDistribution(self,w):
        if w == 'Human Resource ':
            print('Collect work distribution details from the manager')
        else:
            print('Collect work distribution loads from the HR department.')
    def increment(self):
        if self.status=='Foreign':
            self.salary+=(self.salary*0.15)

        elif self.status=='Normal':
            self.salary+=(self.salary*0.1)

        elif self.status=='Part':
            print('Sadly No increment for part timer')

    def employeeDetails(self):
         print(f"Name: {self.name}, Dept {self.dept}")
         print(f"Employee id: {self.id}, Salary: {self.salary}")

class Foreign_employee(Employee):
    def __init__(self,name,id,dept):
        super().__init__(name,id,dept)
        self.salary=30000
        self.status='Foreign'
class Part_time_employee(Employee):
    def __init__(self, name, id, dept):
        super().__init__(name, id, dept)
        self.status = "Part"
        self.salary = 15000

print("1------------------------------------------")
emp1=Employee("Nawaz Ali", 102, "Marketing")
print("2------------------------------------------")
emp1.employeeDetails()
print("3------------------------------------------")
emp1.workDistribution("Marketing")
print("4------------------------------------------")
emp1.increment()
emp1.employeeDetails()
print("5------------------------------------------")
f_emp=Foreign_employee("Nadvi", 311, "Human Resource")
f_emp.employeeDetails()
print("6------------------------------------------")
f_emp.workDistribution("Human Resource")
print("7------------------------------------------")
f_emp.increment()
f_emp.employeeDetails()
print("8------------------------------------------")
p1_emp=Part_time_employee("Asif", 210, "Sales")
p2_emp=Part_time_employee("Olive", 223, "Accounts")
print("9------------------------------------------")
p1_emp.employeeDetails()
print("10------------------------------------------")
p1_emp.workDistribution("Sales")
print("11------------------------------------------")
p2_emp.increment()
print("12------------------------------------------")
p2_emp.employeeDetails()

1------------------------------------------
2------------------------------------------
Name: Nawaz Ali, Dept Marketing
Employee id: 102, Salary: 30000
3------------------------------------------
Collect work distribution loads from the HR department.
4------------------------------------------
Name: Nawaz Ali, Dept Marketing
Employee id: 102, Salary: 33000.0
5------------------------------------------
Name: Nadvi, Dept Human Resource
Employee id: 311, Salary: 30000
6------------------------------------------
Collect work distribution loads from the HR department.
7------------------------------------------
Name: Nadvi, Dept Human Resource
Employee id: 311, Salary: 34500.0
8------------------------------------------
9------------------------------------------
Name: Asif, Dept Sales
Employee id: 210, Salary: 15000
10------------------------------------------
Collect work distribution loads from the HR department.
11------------------------------------------
Sadly No increment for part timer
12------------------------------------------
Name: Olive, Dept Accounts
Employee id: 223, Salary: 15000

In [ ]:
class Exam:
    def __init__(self,marks):
        self.marks = marks
        self.time = 60

    def examSyllabus(self):
        return "Maths , English"
    def examParts(self):
        return "Part 1 - Maths\nPart 2 - English\n"

class ScienceExam(Exam):
    def __init__(self,marks,time,*subj):
        super().__init__(marks)
        self.time=time
        self.subj=list(subj)
        self.parts=len(self.subj)+2

    def examSyllabus(self):
        x = super().examSyllabus()
        return x + ", " + ', '.join(self.subj)
    def examParts(self):
        x=super().examParts()
        for i in range (len(self.subj)):
            if i==0:
                x +=f'Part {i+3} - {self.subj[i]}'
            else:
                 x += f'\nPart {i+3} - {self.subj[i]}'
        return x
    def __str__(self):
        return f"Marks {self.marks} Time {self.time} Number of Parts {self.parts}"

engineering = ScienceExam(100,90,"Physics","HigherMaths")
print(engineering)
print('----------------------------------')
print(engineering.examSyllabus())
print(engineering.examParts())
print('==================================')
architecture = ScienceExam(100,120,"Physics","HigherMaths","Drawing")
print(architecture)
print('----------------------------------')
print(architecture.examSyllabus())
print(architecture.examParts())

Marks 100 Time 90 Number of Parts 4
----------------------------------
Maths , English, Physics, HigherMaths
Part 1 - Maths
Part 2 - English
Part 3 - Physics
Part 4 - HigherMaths
==================================
Marks 100 Time 120 Number of Parts 5
----------------------------------
Maths , English, Physics, HigherMaths, Drawing
Part 1 - Maths
Part 2 - English
Part 3 - Physics
Part 4 - HigherMaths
Part 5 - Drawing

In [ ]:
class Cakes:
    order_list={}
    feedback={}
    def __init__(self,flavor,weight):
        self.flavor=flavor
        self.weight=weight
        self.sugar='Moderate Sugar'
        self.cream='Whipeed Cream'
        self.price=(self.weight*1.2)

        if self.flavor in Cakes.order_list:
            Cakes.order_list[f"{self.flavor} Cake {self.weight}gm"]+=1
        else:
            Cakes.order_list[f"{self.flavor} Cake {self.weight}gm"]=1

    def add_customization(self,sugar,cream):
        self.sugar=sugar
        self.cream=cream
    def cake_details(self):
        print(f"Flavor: {self.flavor} Cake, Weight: {self.weight} gm\nSweetness: {self.sugar}, Cream Type: {self.cream}\nPrice: {self.price} Taka")

    @classmethod
    def give_feedbacks(cls,cake,rev):
        print('Thank you for your valuable feedbacks')
        if cake in cls.feedback:
            cls.feedback[cake].append(rev)
        else:
            cls.feedback[cake]=[rev]

    @classmethod
    def show_feedbacks(self):
        print(Cakes.feedback)

class Cheese_Cakes(Cakes):
    def __init__(self,flavor,weight,types="baked"):
        super().__init__(flavor,weight)
        self.price=weight*1.5
        self.cream="Cream Cheese"
        self.sugar='Moderate Sugar'
        self.types=types

    def cake_details(self):
        print(f"Flavor: {self.flavor} Cake, Weight: {self.weight} gm\nSweetness: {self.sugar}, Cream Type: {self.cream}\nCake Type:{self.types}, Price: {self.price}")

    def add_customization(self):
        print("Sorry! No customization available for cheese cakes.")

    @classmethod
    def give_feedbacks(cls,cake,review):
        super().give_feedbacks(cake,review)
        print("You will get 10% discount for your next purchase!")

order_1=Cakes("Chocolate",500)
order_2=Cakes("Vanilla",800)
print("(1)**********************************")
order_1.cake_details()
print("(1.1)**********************************")
print(Cakes.order_list)
print("(2)**********************************")
order_2.add_customization("Zero","Butter Cream")
order_2.cake_details()
print("(3)**********************************")
Cakes.give_feedbacks("Chocolate Cake","Very Delicious")
Cakes.give_feedbacks("Chocolate Cake","Yummy")
print("(4)**********************************")
Cakes.show_feedbacks()
print("(5)**********************************")
ch_order1=Cheese_Cakes("Red velvet",700)
ch_order1.cake_details()
print("(6)**********************************")
ch_order1.add_customization()
print("(7)**********************************")
ch_order2=Cheese_Cakes("Blue Berry",900,"No Bake")
ch_order2.cake_details()
print("(8)**********************************")
print(Cakes.order_list)
print("(9)**********************************")
Cheese_Cakes.give_feedbacks("Red velvet Cheese Cake","Average")
Cheese_Cakes.give_feedbacks("Blue Berry Cheese Cake","Liked it")
print("(10)**********************************")
Cakes.show_feedbacks()

(1)**********************************
Flavor: Chocolate Cake, Weight: 500 gm
Sweetness: Moderate Sugar, Cream Type: Whipeed Cream
Price: 600.0 Taka
(1.1)**********************************
{'Chocolate Cake 500gm': 1, 'Vanilla Cake 800gm': 1}
(2)**********************************
Flavor: Vanilla Cake, Weight: 800 gm
Sweetness: Zero, Cream Type: Butter Cream
Price: 960.0 Taka
(3)**********************************
Thank you for your valuable feedbacks
Thank you for your valuable feedbacks
(4)**********************************
{'Chocolate Cake': ['Very Delicious', 'Yummy']}
(5)**********************************
Flavor: Red velvet Cake, Weight: 700 gm
Sweetness: Moderate Sugar, Cream Type: Cream Cheese
Cake Type:baked, Price: 1050.0
(6)**********************************
Sorry! No customization available for cheese cakes.
(7)**********************************
Flavor: Blue Berry Cake, Weight: 900 gm
Sweetness: Moderate Sugar, Cream Type: Cream Cheese
Cake Type:No Bake, Price: 1350.0
(8)**********************************
{'Chocolate Cake 500gm': 1, 'Vanilla Cake 800gm': 1, 'Red velvet Cake 700gm': 1, 'Blue Berry Cake 900gm': 1}
(9)**********************************
Thank you for your valuable feedbacks
You will get 10% discount for your next purchase!
Thank you for your valuable feedbacks
You will get 10% discount for your next purchase!
(10)**********************************
{'Chocolate Cake': ['Very Delicious', 'Yummy'], 'Red velvet Cheese Cake': ['Average'], 'Blue Berry Cheese Cake': ['Liked it']}

In [ ]:
class myList:

    def __init__(self,*args):
        self.list1=list(args)
        self.list2=[]
        self.sum1=0
        self.avg=0
        self.list2.extend(self.list1)
    def sum(self):
        for i in self.list1:
            self.sum1+=i

        print('Sum',self.sum1)
    def merge(self,*args2):
        self.list1=[]
        for i in range (len(args2)):
            self.list1.append(args2[i])
            self.list2.append(args2[i])
    def average(self):
        if len(self.list2) == 0:
            self.avg = 0
            print('AVG:',self.avg)
        else:
            self.avg = self.sum1 / len(self.list2)
            print('AVG:',self.avg)
            print(len(self.list2))
l1 =  myList(2,3,4,5,6) #you might need a list inside your class to store the values
l1.sum()
l1.merge(4,5,9)
l1.sum()
l1.average()
print('-----------------------------')
l2 =  myList()
l2.average()
l2.merge(1,2,4,8)
l2.sum()

Sum 20
Sum 38
AVG: 4.75
8
-----------------------------
AVG: 0
Sum 15

In [ ]:
class Account :
    count=0
    def __init__(self,name,age,occ,amount):
        self.name=name
        self.age=age
        self.occ=occ
        self.amount=amount
        Account.count+=1
    def addMoney(self,new):
        self.amount+=new
    def withdrawMoney(self,draw):
        if self.amount>=draw:
            self.amount-=draw
        else:
            pass
    def printDetails(self):
        print(f'Name: {self.name}')
        print(f'Age : {self.age}')
        print(f'Occupation : {self.occ}')
        print(f'Amount : {self.amount}')
# Write your code here

print('No of account holders:', Account.count)
print("=========================")
p1 = Account("Abdul", 45, "Service Holder", 500000)
p1.addMoney(300000)
p1.printDetails()
print("=========================")
p2 = Account("Rahim", 55, "Businessman", 700000)
p2.withdrawMoney(700000)
p2.printDetails()
print("=========================")
p3 = Account("Ashraf", 62, "Govt. Officer", 200000)
p3.withdrawMoney(250000)
p3.printDetails()
print("=========================")
print('No of account holders:', Account.count)

No of account holders: 0
=========================
Name: Abdul
Age : 45
Occupation : Service Holder
Amount : 800000
=========================
Name: Rahim
Age : 55
Occupation : Businessman
Amount : 0
=========================
Name: Ashraf
Age : 62
Occupation : Govt. Officer
Amount : 200000
=========================
No of account holders: 3

In [ ]:
class Smartphone:
    def __init__(self,name=None):
        self.name=name
        self.features = {}
    def addFeature(self, feature, value):
        if self.name is None:
            print("Feature can not be added without phone name")
        else:
            if feature in self.features:
                self.features[feature].append(value)
            else:
                self.features[feature] = [value]
    def setName(self,new):
        self.name=new
    def printDetail(self):
        print(f'Phone : {self.name}')
        for i,j in self.features.items():
            x= ','.join(j)
            print(f'{i} : {x}')

# Do not change the following lines of code.
s1 = Smartphone()
print("=================================")
s1.addFeature("Display", "6.1 inch")
print("=================================")
s1.setName("Samsung Note 20")
s1.addFeature("Display", "6.1 inch")
s1.printDetail()
print("=================================")
s2 = Smartphone("Iphone 12 Pro")
s2.addFeature("Display", "6.2 inch")
s2.addFeature("Ram", "6 GB")
print("=================================")
s2.printDetail()
s2.addFeature("Display", "Amoled panel")
s2.addFeature("Ram", "DDR5")
print("=================================")
s2.printDetail()
print("=================================")

=================================
Feature can not be added without phone name
=================================
Phone : Samsung Note 20
Display : 6.1 inch
=================================
=================================
Phone : Iphone 12 Pro
Display : 6.2 inch
Ram : 6 GB
=================================
Phone : Iphone 12 Pro
Display : 6.2 inch,Amoled panel
Ram : 6 GB,DDR5
=================================

In [ ]:
class Student:
    total_students = 0
    cse_students = 0
    bba_students = 0

    def __init__(self, name, department):
        self.name = name
        self.department = department
        Student.total_students += 1
        self.studentNumber = Student.total_students
        if self.department == "CSE":
            Student.cse_students += 1
            self.serialNumber = Student.cse_students
        elif self.department == "BBA":
            Student.bba_students += 1
            self.serialNumber = Student.bba_students

    def individualInfo(self):
        print(f"{self.name} is from {self.department} department.")
        print(f"Serial of {self.name} among all students is: {self.studentNumber}")
        print(f"Serial of {self.name} in {self.department} department is: {self.serialNumber}")

    @classmethod
    def totalInfo(cls):
        print("#############################")
        print(f"Total Number of Student: {cls.total_students}")
        print(f"Total Number of CSE Student: {cls.cse_students}")
        print(f"Total Number of BBA Student: {cls.bba_students}")
        print("============================")

# Driver code
s1 = Student("Naruto", "CSE")
s1.individualInfo()
s1.totalInfo()

s2 = Student("Sakura", "BBA")
s2.individualInfo()
s2.totalInfo()

s3 = Student("Shikamaru", "CSE")
s3.individualInfo()
s3.totalInfo()

s4 = Student("Deidara", "BBA")
s4.individualInfo()
s4.totalInfo()

Naruto is from CSE department.
Serial of Naruto among all students is: 1
Serial of Naruto in CSE department is: 1
#############################
Total Number of Student: 1
Total Number of CSE Student: 1
Total Number of BBA Student: 0
============================
Sakura is from BBA department.
Serial of Sakura among all students is: 2
Serial of Sakura in BBA department is: 1
#############################
Total Number of Student: 2
Total Number of CSE Student: 1
Total Number of BBA Student: 1
============================
Shikamaru is from CSE department.
Serial of Shikamaru among all students is: 3
Serial of Shikamaru in CSE department is: 2
#############################
Total Number of Student: 3
Total Number of CSE Student: 2
Total Number of BBA Student: 1
============================
Deidara is from BBA department.
Serial of Deidara among all students is: 4
Serial of Deidara in BBA department is: 2
#############################
Total Number of Student: 4
Total Number of CSE Student: 2
Total Number of BBA Student: 2
============================

In [ ]:
class Fruit:
    Total_order = 0

    def __init__(self, Order_ID, weight):
        self.Order_ID = Order_ID
        self.weight = weight
        Fruit.Total_order += 1

    def __str__(self):
        return f"{self.Order_ID}, Weight: {self.weight}"


class Mango(Fruit):
    def __init__(self, Order_ID, weight, variety, unit_price):
        super().__init__(Order_ID, weight)
        self.variety = variety
        self.unit_price = unit_price

    def __str__(self):
        total_price = self.weight * self.unit_price
        return f"{super().__str__()}, Variety: {self.variety}, Total Price: {total_price}"

    def __add__(self, other):
        total_price = (self.weight * self.unit_price) + (other.weight * other.unit_price)
        return f"The total Price of the orders are: {total_price}"
class JackFruit(Fruit):
    def __init__(self, Order_ID, weight, unit_price):
        super().__init__(Order_ID, weight)
        self.unit_price = unit_price

    def __str__(self):
        total_price = self.weight * self.unit_price
        return f"{super().__str__()}, Total Price: {total_price}"
    def __add__(self, other):
        total_price = (self.weight * self.unit_price) + (other.weight * other.unit_price)
        return f"The total Price of the orders are: {total_price}"

m1=Mango("Order Id 1", 5,"GopalVog",250)
print(m1)
m2=Mango("Order Id 2", 5,"HariVanga", 230)
print(m2)
j1=JackFruit("Order Id 3", 5,250)
print(j1)
j2=JackFruit("Order Id 4", 4,210)
print(j2)
print("Total number of Orders: "+str(Fruit.Total_order))
print("==================")
print(m1+m2)
print("==================")
print(j1+j2)

Order Id 1, Weight: 5, Variety: GopalVog, Total Price: 1250
Order Id 2, Weight: 5, Variety: HariVanga, Total Price: 1150
Order Id 3, Weight: 5, Total Price: 1250
Order Id 4, Weight: 4, Total Price: 840
Total number of Orders: 4
==================
The total Price of the orders are: 2400
==================
The total Price of the orders are: 2090

Write the CSEStudent class with the required methods to give the following outputs as shown.Hints:
Each course has 3 credits.
GPA = sum( per course grade * per course credit) / sum(credit attended in that semester)
Grading policy:  mark>=85: 4.0 ; 80<=mark<=84: 3.3;70<=mark<=79:3.0 ;65<=mark<=69: 2.3; 57<=mark<=64:2.0 ; 55<=mark<=56:1.3; 50<=mark<=54:1.0; >50:0.0

In [ ]:
class Student:
    def __init__(self,name,ID):
        self.name = name
        self.ID = ID
    def Details(self):
        return "Name: "+self.name+"\n"+"ID: "+self.ID+"\n"
#Write your code here

class CSEStudent(Student):
    def __init__(self,name,id,semester):
        super().__init__(name,id)
        self.naame=name
        self.id=id
        self.semester=semester
        self.courses={}
    def Details(self):
        x=super().Details()
        return f'{x}Current Semester: {self.semester}'
    def addCourseWithMarks(self,*info):
        for i in range(0,len(info),2):
            self.courses[info[i]]=info[i+1]

    def showGPA(self):
        sum=0
        print(f'{self.name } has taken {len(self.courses)} course')
        for i,j in self.courses.items():
            if j>85:
                cg=4
            elif 80<j<84:
                cg=3.5
            elif 75<j<80:
                cg=3.3
            elif 60<j<74:
                cg=3.00
            else:
                cg=2.00

            print(f"{i} : {cg}")
            sum+=(cg)
        gpa=sum/len(self.courses)
        print(f"GPA of {self.name} is {gpa}")

#Write your code here

Bob = CSEStudent('Bob','20301018','Fall 2020')
Carol = CSEStudent("Carol","16301814","Fall 2020")
Anny = CSEStudent("Anny","18201234","Fall 2020")
print("#########################")
print(Bob.Details())
print("#########################")
print(Carol.Details())
print("#########################")
print(Anny.Details())
print("#########################")
Bob.addCourseWithMarks("CSE111",83.5,"CSE230",73.0,"CSE260",92.5)
Carol.addCourseWithMarks("CSE470",62.5,"CSE422",69.0,"CSE460",76.5,"CSE461",87.0)
Anny.addCourseWithMarks("CSE340",45.5,"CSE321",95.0,"CSE370",91.0)
print("----------------------------")
Bob.showGPA()
print("----------------------------")
Carol.showGPA()
print("----------------------------")
Anny.showGPA()

#########################
Name: Bob
ID: 20301018
Current Semester: Fall 2020
#########################
Name: Carol
ID: 16301814
Current Semester: Fall 2020
#########################
Name: Anny
ID: 18201234
Current Semester: Fall 2020
#########################
----------------------------
Bob has taken 3 course
CSE111 : 3.5
CSE230 : 3.0
CSE260 : 4
GPA of Bob is 3.5
----------------------------
Carol has taken 4 course
CSE470 : 3.0
CSE422 : 3.0
CSE460 : 3.3
CSE461 : 4
GPA of Carol is 3.325
----------------------------
Anny has taken 3 course
CSE340 : 2.0
CSE321 : 4
CSE370 : 4
GPA of Anny is 3.3333333333333335

In [ ]:
class Student:
    def __init__(self,name,ID):
        self.name = name
        self.ID = ID
    def Details(self):
        return "Name: "+self.name+"\n"+"ID: "+self.ID+"\n"
#Write your code here

class CSEStudent(Student):
    def __init__(self,name,id,semester):
        super().__init__(name,id)
        self.naame=name
        self.id=id
        self.semester=semester
        self.courses={}
    def Details(self):
        x=super().Details()
        return f'{x}Current Semester: {self.semester}'
    def addCourseWithMarks(self,*info):
        for i in range(0,len(info),2):
            if info[i+1]>85:
                cg=4
            elif 80<info[i+1]<84:
                cg=3.5
            elif 75<info[i+1]<80:
                cg=3.3
            elif 60<info[i+1]<74:
                cg=3.00
            else:
                cg=2.00
            self.courses[info[i]]=cg

    def showGPA(self):
        sum=0
        print(f'{self.name } has taken {len(self.courses)} course')
        for i,j in self.courses.items():
            print(f"{i}: {j}")
            sum+=j
        gpa=sum/len(self.courses)
        print(f"GPA of {self.name} is {gpa}")

#Write your code here

Bob = CSEStudent('Bob','20301018','Fall 2020')
Carol = CSEStudent("Carol","16301814","Fall 2020")
Anny = CSEStudent("Anny","18201234","Fall 2020")
print("#########################")
print(Bob.Details())
print("#########################")
print(Carol.Details())
print("#########################")
print(Anny.Details())
print("#########################")
Bob.addCourseWithMarks("CSE111",83.5,"CSE230",73.0,"CSE260",92.5)
Carol.addCourseWithMarks("CSE470",62.5,"CSE422",69.0,"CSE460",76.5,"CSE461",87.0)
Anny.addCourseWithMarks("CSE340",45.5,"CSE321",95.0,"CSE370",91.0)
print("----------------------------")
Bob.showGPA()
print("----------------------------")
Carol.showGPA()
print("----------------------------")
Anny.showGPA()

#########################
Name: Bob
ID: 20301018
Current Semester: Fall 2020
#########################
Name: Carol
ID: 16301814
Current Semester: Fall 2020
#########################
Name: Anny
ID: 18201234
Current Semester: Fall 2020
#########################
----------------------------
Bob has taken 3 course
CSE111: 3.5
CSE230: 3.0
CSE260: 4
GPA of Bob is 3.5
----------------------------
Carol has taken 4 course
CSE470: 3.0
CSE422: 3.0
CSE460: 3.3
CSE461: 4
GPA of Carol is 3.325
----------------------------
Anny has taken 3 course
CSE340: 2.0
CSE321: 4
CSE370: 4
GPA of Anny is 3.3333333333333335

In [ ]:
class Transport:                                                    #Good One
    total_traveller = 0

    def __init__(self, name, fare):
        self.name = name
        self.baseFare = fare

    def __str__(self):
        s =  "Name: "+self.name+", Base fare: "+str(self.baseFare)
        return s

class Bus(Transport):
    def __init__(self,place,fare):
        super().__init__(place,fare)
        print(f'Base fare of volvo is {fare} ')
        self.dict1={}


    def addPassengerWithBags(self, *info):
        fare= self.baseFare
        for j in range(0, len(info), 2):
            if 3 <= info[j + 1] <= 5:
                fare += 60
            elif info[j + 1] > 5:
                fare += 105
            else:
                fare = self.baseFare
            self.dict1[info[j]] = fare
        Transport.total_traveller+=len(self.dict1)

    def __str__(self):
            x = super().__str__()
            x += f'\nTotal Passengers: {len(self.dict1)}\n'
            x += f'Passenger Details:\n'
            for passenger, fare in self.dict1.items():
                x += f'Name: {passenger}, Fare: {fare}\n'
            return x
class Train(Bus):
    def __init__(self, name, fare):
        super().__init__(name, fare)


t1 = Bus("Volvo", 950)
print("=================================")
t1.addPassengerWithBags("David", 6,  "Mike", 1, "Carol", 3)
print("=================================")
print(t1)
print("=================================")
t2 = Train("Silk City", 850)
print("=================================")
t2.addPassengerWithBags("Bob", 2, "Simon", 4)
print("=================================")
print(t2)
print("=================================")
print("Total Passengers in Transport: ", Transport.total_traveller)

Base fare of volvo is 950
=================================
=================================
Name: Volvo, Base fare: 950
Total Passengers: 3
Passenger Details:
Name: David, Fare: 1055
Name: Mike, Fare: 950
Name: Carol, Fare: 1010

=================================
Base fare of volvo is 850
=================================
=================================
Name: Silk City, Base fare: 850
Total Passengers: 2
Passenger Details:
Name: Bob, Fare: 850
Name: Simon, Fare: 910

=================================
Total Passengers in Transport:  5

**Verry** **Verrrrry** **Importannnnnntttttttttttttt**

In [ ]:
class AppleProduct: #VVI
    def __init__(self, name, model, base_price):
        self.name = name
        self.model = model
        self.base_price = base_price
    def companyInfo(self):
        st = ("Company Name: Apple\nFouder: Steve Jobs, Steve Wozniak, Ronald Wayne\nCurrent CEO: Tim Cook\nAddress: Apple Inc, 2511 Laguna Blvd, Elk Grove, CA 95758, United States")
        return st
    def feature(self):
        st = (f"Name: {self.name}\nProduct Model: {self.model}\nHardware Quality: Excellent Hardwares\nGuarantee/ Warranty: Apple Care")
        return st
    def __str__(self):
        print('This is apple product.')
    def calculatePrice(self):
        print('Total Price:', self.base_price)


class MacBookPro2020(AppleProduct):
    def __init__(self, name, model, ram, chip, tax,base_price=1299):
        super().__init__(name, model, base_price)
        self.ram = ram
        self.chip = chip
        self.tax = tax
        self.total_price=0

    def feature(self):
        st = super().feature() + f"\nRAM: {self.ram}GB\nChip: {self.chip}"
        return st

    def calculatePrice(self):
        total_tax=(self.base_price*self.tax)/100
        self.total_price=total_tax+self.base_price
        print(f'Base Price: {self.base_price}\nTax : {self.tax}%\nTotal Price: {self.total_price}')

    def __str__(self):
        return f"{self.feature()}\n{self.companyInfo()}"

    def __add__(self, other):
        return self.total_price+other.total_price
class iPhone12(AppleProduct):
    def __init__(self, name, model,ram,chip,tax,base_price=799):
        super().__init__(name, model, base_price)
        self.ram = ram
        self.chip = chip
        self.tax = tax
        self.total_price=0

    def feature(self):
        st = super().feature() + f"\nRAM: {self.ram}GB\nChip: {self.chip}"
        return st

    def calculatePrice(self):
        total_tax=(self.base_price*self.tax)/100
        self.total_price=total_tax+self.base_price
        print(f'Base Price: {self.base_price}\nTax : {self.tax}%\nTotal Price: {self.total_price}')
    def __str__(self):
        return f"{self.feature()}\n{self.companyInfo()}"

    def __add__(self, other):
            self.total_price+other.total_price

m1 = MacBookPro2020('MacBook', 'MacBookPro2020', 8, 'M1', 10)
print(m1)
print('====================================')
m1.calculatePrice()
print('###################################')
iphone = iPhone12('iPhone', 'iPhone 12', 8, 'A14', 5)
print(iphone)
print('====================================')
iphone.calculatePrice()
print('###################################')
print('Total Price of these two products: ',end='')
print('%.2f Dollars'%(m1 + iphone))

Name: MacBook
Product Model: MacBookPro2020
Hardware Quality: Excellent Hardwares
Guarantee/ Warranty: Apple Care
RAM: 8GB
Chip: M1
Company Name: Apple
Fouder: Steve Jobs, Steve Wozniak, Ronald Wayne
Current CEO: Tim Cook
Address: Apple Inc, 2511 Laguna Blvd, Elk Grove, CA 95758, United States
====================================
Base Price: 1299
Tax : 10%
Total Price: 1428.9
###################################
Name: iPhone
Product Model: iPhone 12
Hardware Quality: Excellent Hardwares
Guarantee/ Warranty: Apple Care
RAM: 8GB
Chip: A14
Company Name: Apple
Fouder: Steve Jobs, Steve Wozniak, Ronald Wayne
Current CEO: Tim Cook
Address: Apple Inc, 2511 Laguna Blvd, Elk Grove, CA 95758, United States
====================================
Base Price: 799
Tax : 5%
Total Price: 838.95
###################################
Total Price of these two products: 2267.85 Dollars

In [ ]:
class Restaurant: #VVVVVVIIIIIII
    def __init__(self, name, type,location):
        self.__name = name
        self.__type = type
        self.__location = location
    def addToMenu(self):
        print('New item(s) added to menu')
    def placeOrder(self):
        print(f'A new order placed at {self.__location} branch')
    def __str__(self):
        return "Name:{}\nType:{}\nLocation:{}".format(self.name,self.type,self.location)

class KacchiDine(Restaurant):
    def __init__(self,Location,*items,name='KacchiDine',type='Bengali'):
        super().__init__(name,type,Location)
        self.items={}
        self.total=0
        for i in items:
            item,price=i.split('-')
            self.items[item]=int(price)

    def addToMenu(self,*new):
        for i in new:
            item,price=i.split('-')
            self.items[item]=int(price)
        print('New item(s) added to menu')

    def placeOrder(self,*order):
        new=0
        for i in order:
            item,quantity=i.split('-')
            if item in self.items:
                x=True
                new+=int(quantity)*(self.items[item])
            else:
                x=False
                break
        if x==True:
            self.total+=new
            print(f'Order Placed at {self._Restaurant__location}')
        else:
            print('Cannot Place order Not all items in the menue')


    def updateMenu(self,item,price):
        if item in self.items:
            self.items[item]=int(price)
        else:
            print('Cannot Update menu no such a thing exists!')

    def __str__(self):
        return f'Restaurant Details :\nName:{self._Restaurant__name}\nType:{self._Restaurant__type}\nLocation:{self._Restaurant__location}\nMenu:{self.items}\nTotal_sale:{self.total}'

branch1 = KacchiDine("Banani", "Kacchi-250", "Tehari-220", "Borhani-50")
print(branch1)
print("===========1============")
branch1.addToMenu("Firni-60")
print("===========2============")
branch1.placeOrder("Firni-2", "Kacchi-1")
print("===========3============")
print(branch1)
print("===========4============")
branch1.updateMenu("Polao", 240)
print("===========5============")
branch2 = KacchiDine('Dhanmondi', 'Kacchi-270', "Tehari-210")
print(branch2)
print("===========6============")
branch2.placeOrder("Kacchi-1", "Kabab-1")
print("===========7============")
branch2.addToMenu("Roast-160", "Jorda-40")
print("===========8============")
branch2.placeOrder("Tehari-3")
print("===========9============")
branch2.updateMenu("Roast", 140)
print("===========10============")
branch2.placeOrder("Jorda-1")
print("===========11============")
print(branch2)
print("===========12============")

Restaurant Details :
Name:KacchiDine
Type:Bengali
Location:Banani
Menu:{'Kacchi': 250, 'Tehari': 220, 'Borhani': 50}
Total_sale:0
===========1============
New item(s) added to menu
===========2============
Order Placed at Banani
===========3============
Restaurant Details :
Name:KacchiDine
Type:Bengali
Location:Banani
Menu:{'Kacchi': 250, 'Tehari': 220, 'Borhani': 50, 'Firni': 60}
Total_sale:370
===========4============
Cannot Update menu no such a thing exists!
===========5============
Restaurant Details :
Name:KacchiDine
Type:Bengali
Location:Dhanmondi
Menu:{'Kacchi': 270, 'Tehari': 210}
Total_sale:0
===========6============
Cannot Place order Not all items in the menue
===========7============
New item(s) added to menu
===========8============
Order Placed at Dhanmondi
===========9============
===========10============
Order Placed at Dhanmondi
===========11============
Restaurant Details :
Name:KacchiDine
Type:Bengali
Location:Dhanmondi
Menu:{'Kacchi': 270, 'Tehari': 210, 'Roast': 140, 'Jorda': 40}
Total_sale:670
===========12============

In [ ]:
class Library: #VVVVVVIIIIIIII
    Total_book = 1000
    borrow_data = {}

    def __init__(self,n,id):
        self.student_name = n
        self.student_id = id

    def borrowbook(self):
        print("A book is borrowed!")

    def __str__(self):
        return "Library: XYZ"

class Student(Library):
    def __init__(self,name,id):
        super().__init__(name,id)
        self.books=[]

    def borrowbook(self, book, id=None):
        if book not in Library.borrow_data:
            self.books.append(book)
            Library.borrow_data[book] = [self.student_name]
            if id is not None:
                print(f"The '{book}' book with unique id {id} is borrowed by {self.student_name}({self.student_id})")
            else:
                print(f"The '{book}' book is borrowed by {self.student_name}({self.student_id})")
        else:
            print(f'Sorry {self.student_name} this book is already borrowed by {" ".join(Library.borrow_data[book])}')
        Library.Total_book -= 1

    def __str__(self):
        return f"Library: XYZ\nStudent Name : {self.student_name} ID : {self.student_id}\nBooks Borrowed {','.join(self.books)}"

    def returnAllBooks(self):
        print(f'All books are returned by {self.student_name}')
        x = []
        for i, j in Library.borrow_data.items():
            if self.student_name in j:
                Library.Total_book -= 1
                x.append(i)
        for i in x:
            del Library.borrow_data[i]
        for i,j in self.dict.items()
s1 = Student("Alice",18101259)
s1.borrowbook("The Alchemist", "Hdw652")
print("===============")
print(s1)
print("===============")
print(Library.borrow_data)
print("===============")
s1.borrowbook("Wuthering Heights")
print("===============")
print(s1)
print("===============")
s2= Student("David",18141777)
s2.borrowbook("The Alchemist", "Hdw652")
print("===============")
s2.borrowbook("The Vampyre")
print("===============")
print(Library.borrow_data)
print("===============")
s1.returnAllBooks()
print("===============")
print(Library.borrow_data)

The 'The Alchemist' book with unique id Hdw652 is borrowed by Alice(18101259)
===============
Library: XYZ
Student Name : Alice ID : 18101259
Books Borrowed The Alchemist
===============
{'The Alchemist': ['Alice']}
===============
The 'Wuthering Heights' book is borrowed by Alice(18101259)
===============
Library: XYZ
Student Name : Alice ID : 18101259
Books Borrowed The Alchemist,Wuthering Heights
===============
Sorry David this book is already borrowed by Alice
===============
The 'The Vampyre' book is borrowed by David(18141777)
===============
{'The Alchemist': ['Alice'], 'Wuthering Heights': ['Alice'], 'The Vampyre': ['David']}
===============
All books are returned by Alice
===============
{'The Vampyre': ['David']}

In [ ]:
class Player: #VVVVVVVVIIIIII
    database = {}
    playerNo = 0
    def __init__(self, name, team, jerseyNo):
        self.name = name
        self.team = team
        self.jerseyNo = jerseyNo
    def __str__(self):
        return "Name:{}\nTeam:{}\nJersey No:{}".format(self.name,self.team,self.jerseyNo)
class FootballPlayer(Player):
    def __init__(self,name, team, jerseyNo,goals,r=None):
        super().__init__(name,team,jerseyNo)
        self.goals=goals
        if r==None:
            self.r='Not yet fixed'
        else:
            self.r=r
        self.l=[]
        self.l.extend([self.name,self.team,self.jerseyNo,self.goals,self.r])
        Player.playerNo+=1
        first,second=self.name.split(' ')
        self.id= str(Player.playerNo)+first[0]+second[0]+str(self.jerseyNo)
        Player.database[self.id]=self.l

    def __str__(self):
        x= super().__str__()
        return f"Player ID:{self.id}\n{x}\nGoals:{self.goals}\nRetirementyear{self.r}"
    @classmethod
    def createPlayer(cls,name, team, jerseyNo,goals,retirement):
        obj=cls(name, team, jerseyNo,goals,retirement)
        return obj

print("Number of players:", Player.playerNo)
print("Player Database:", Player.database)
print("#################################")
p1 = FootballPlayer("Lionel Messi","Barcelona",10,231)
print("------Details of the player------")
print(p1)
print("#################################")
p2 = FootballPlayer("Cristiano Ronaldo","Juventus",7,215)
print("------Details of the player------")
print(p2)
print("#################################")
p3 = FootballPlayer.createPlayer("Miroslav Klose","Lazio",11, 71,"11 Aug,2014")
print("------Details of the player------")
print(p3)
print("#################################")
print("Number of players:",Player.playerNo)
print("Player Database:",Player.database)

Number of players: 0
Player Database: {}
#################################
------Details of the player------
Player ID:1LM10
Name:Lionel Messi
Team:Barcelona
Jersey No:10
Goals:231
RetirementyearNot yet fixed
#################################
------Details of the player------
Player ID:2CR7
Name:Cristiano Ronaldo
Team:Juventus
Jersey No:7
Goals:215
RetirementyearNot yet fixed
#################################
------Details of the player------
Player ID:3MK11
Name:Miroslav Klose
Team:Lazio
Jersey No:11
Goals:71
Retirementyear11 Aug,2014
#################################
Number of players: 3
Player Database: {'1LM10': ['Lionel Messi', 'Barcelona', 10, 231, 'Not yet fixed'], '2CR7': ['Cristiano Ronaldo', 'Juventus', 7, 215, 'Not yet fixed'], '3MK11': ['Miroslav Klose', 'Lazio', 11, 71, '11 Aug,2014']}

In [ ]:
class A:
    temp = -5
    def __init__(self):
        self.sum = 0
        self.y = 0
        self.y = self.temp - 3
        self.sum = A.temp + 2
    def methodA(self, m ,n):
        x = 1
        A.temp += 1
        self.y = self.y + m + self.temp
        x = x + 1 + n
        self.sum = self.sum + x + self.y
        print(f"{x} {self.y} {self.sum}")

class B(A):
    x = -10
    def __init__(self, b = None):
        super().__init__()
        self.y = 4
        if b == None:
            self.y = self.temp + 3
            self.temp -= 2
        else:
            self.sum = b.sum
            B.x = b.x
    def methodA(self, m, n):
        x = 1
        self.temp += 1
        self.y = self.y + m + self.temp
        super().methodA(x, m)
        self.sum = self.sum + x + self.y
        print(f"{x} {self.y} {self.sum}")
    def methodB(self, m, n):
        y = 3
        y = y + self.y
        B.x = self.y + 3 + self.temp
        self.methodA(B.x, y)
        self.sum = self.x + y + self.sum
        print(f"{B.x} {y} {self.sum}")

b1 = B()
b2 = B(b1)
b2.methodB(1,2)

4 -1 0
1 -1 0
2 7 9

In [ ]:
class A:
    temp = 8
    def __init__(self):
        self.y = A.temp - 5
        self.sum = self.temp + 3
        self.temp += 2
    def methodA(self, m,  n):
        x = 4
        self.y = self.y + m + (A.temp)
        x = x - 2 + n
        print(x, self.y, self.sum)
        x = self.y + self.methodB(4, -3)
        self.sum = self.sum + x + A.temp
        self.methodB(-4, self.sum, 3)
    def methodB(self, m,  n):
        y = 5
        y = y + self.y
        self.sum = B.x + y + n
        print(B.x, y, self.sum)
class B(A):
    x = -3
    def __init__(self, obj=None):
        super().__init__()
        if obj != None:
            obj.sum = self.temp + 13
        self.y = A.temp + 3
        self.sum = 6 + A.temp + B.x
    def methodB(self, m, n, y=0):
        y = y + self.y + n
        B.x = m + self.y + n
        A.temp+=2
        self.sum = B.x + y + A.temp
        print(B.x, y, self.sum)
        return y


b1 = B()
b2 = B(b1)
b1.methodA(-4, 5)

7 15 23
16 12 38
86 93 191

In [ ]:
class User:
    def __init__(self,name,place,ride='Single'):
        self.name=name
        self.place=place
        self.ride=ride
        self.x=None
    def status(self):
        if self.x==None:
            print(f'Status: {self.name} is looking for a {self.ride} ride')
        elif self.x=='A':
            print(f'Status: {self.name} has been droped')

class Uber:
    def __init__(self,number,type,*routes):
        self.number=number
        self.type=type
        self.routes=list(routes)
    def pick(self,*passangers):
        for i in passangers:
            if i.ride==self.type and i.place in self.routes:
                print(f'{i.name} has been picked up')
                i.x='A'
            elif i.place not in self.routes:
                print(f'{i.name} destination is different from this car route')
            elif i.ride!=self.type:
                print(f'{i.name} is looking for a different ride')

    def  details(self):
        print(f'Car number {self.number}')
        print(f'Car type:{self.type}')
        print(f'Routes : {"--->".join(self.routes)}')


user1 = User("Brooks", "Banani", "Shared")
user2 = User("Jocelyn", "Uttara")
user3 = User("Robert", "Gulshan", "Shared")
user4 = User("Langdon", "Mohakhali", "Shared")


user1.status()
user2.status()
user3.status()
user4.status()
print("----------------------------------")
car1 = Uber("0K32BH", "Shared", "Mohakhali", "Banani", "Nikunja", "Uttara")
car1.details()
print("----------------------------------")
car1.pick(user1,user2,user3,user4)
print("----------------------------------")
user1.status()
user2.status()
user3.status()
user4.status()
print("----------------------------------")
car2 = Uber("5GD2BD", "Single", "Uttara")
car3 = Uber("4T12FR", "Shared", "Gulshan", "Bashundhara")
car2.details()
car3.details()
print("----------------------------------")
car2.pick(user2, user3)
print("----------------------------------")
car3.pick(user3)
print("----------------------------------")
user2.status()
user3.status()

Status: Brooks is looking for a Shared ride
Status: Jocelyn is looking for a Single ride
Status: Robert is looking for a Shared ride
Status: Langdon is looking for a Shared ride
----------------------------------
Car number 0K32BH
Car type:Shared
Routes : Mohakhali--->Banani--->Nikunja--->Uttara
----------------------------------
Brooks has been picked up
Jocelyn is looking for a different ride
Robert destination is different from this car route
Langdon has been picked up
----------------------------------
Status: Brooks has been droped
Status: Jocelyn is looking for a Single ride
Status: Robert is looking for a Shared ride
Status: Langdon has been droped
----------------------------------
Car number 5GD2BD
Car type:Single
Routes : Uttara
Car number 4T12FR
Car type:Shared
Routes : Gulshan--->Bashundhara
----------------------------------
Jocelyn has been picked up
Robert destination is different from this car route
----------------------------------
Robert has been picked up
----------------------------------
Status: Jocelyn has been droped
Status: Robert has been droped

In [ ]:
class Shape:

  def __init__(self, name='Default', height=0, base=0):
    self.area = 0
    self.name = name
    self.height = height
    self.base = base

  def get_height_base(self):
    return "Height: "+str(self.height)+",Base: "+str(self.base)



class triangle(Shape):
    def __init__(self,name='Defualt',height=0,base=0):
        super().__init__(name,height,base)

    def calcArea(self):
        self.area = 0.5*self.height*self.base

    def printDetail(self):
        print(f"Shape name: {self.name}")
        st = f"{self.get_height_base()}\nArea: {float(self.area)}"
        return st

class trapezoid(Shape):
  def __init__(self,name,height,base,side):
     super().__init__(name,height,base)
     self.side = side

  def calcArea(self):
    self.area = 0.5*self.height*(self.base+self.side)

  def printDetail(self):
    print(f"Shape name: {self.name}")
    st =f"{self.get_height_base()}, Side_A: {self.side}\nArea: {float(self.area)}"
    return st




tri_default = triangle()
tri_default.calcArea()
print(tri_default.printDetail())
print('--------------------------')
tri = triangle('Triangle', 10, 5)
tri.calcArea()
print(tri.printDetail())
print('---------------------------')
trap = trapezoid('Trapezoid', 10, 6, 4)
trap.calcArea()
print(trap.printDetail())

Shape name: Defualt
Height: 0,Base: 0
Area: 0.0
--------------------------
Shape name: Triangle
Height: 10,Base: 5
Area: 25.0
---------------------------
Shape name: Trapezoid
Height: 10,Base: 6, Side_A: 4
Area: 50.0

In [ ]:
class KK_tea: #VVVVVIII
    count=0
    dict1={}
    def __init__(self,price,bags=50):
        self.price=price
        self.bags=bags
        self.status=None
        self.name='KK Regular Tea'
        KK_tea.dict1[self.name]=KK_tea.count
    @classmethod
    def update_sold_status_regular(cls,*t):
        for i in t:
            cls.count+=1
            cls.dict1[i.name]=cls.count
            i.status=True
    @classmethod
    def total_sales(cls):
        print(f"Total sales: {cls.dict1}")

    def product_detail(self):
        self.weight=2*(self.bags)
        print(f"Name: {self.name}, Weight: {self.weight}")
        print(f"Tea Bags: {self.bags}, Price: {self.price}")
        print(f"Status: {self.status} ")

class KK_flavoured_tea(KK_tea):
    def __init__(self,name,price,bags):
        super().__init__(price,bags)
        self.name="KK "+name+" Tea"
    @classmethod
    def update_sold_status_flavoured(cls,*t):
       for i in t:
            if i.name not in cls.dict1:
                cls.dict1[i.name]=1
            else:
                cls.dict1[i.name]+=1

            cls.count+=1
            i.status=True

t1 = KK_tea(250)
print("-----------------1-----------------")
t1.product_detail()
print("-----------------2-----------------")
KK_tea.total_sales()
print("-----------------3-----------------")
t2 = KK_tea(470, 100)
t3 = KK_tea(360, 75)
KK_tea.update_sold_status_regular(t1, t2, t3)
print("-----------------4-----------------")
t3.product_detail()
print("-----------------5-----------------")
KK_tea.total_sales()
print("-----------------6-----------------")
t4 = KK_flavoured_tea("Jasmine", 260, 50)
t5 = KK_flavoured_tea("Honey Lemon", 270, 45)
t6 = KK_flavoured_tea("Honey Lemon", 270, 45)
print("-----------------7-----------------")
t4.product_detail()
print("-----------------8-----------------")
t6.product_detail()
print("-----------------9-----------------")
KK_flavoured_tea.update_sold_status_flavoured(t4, t5, t6)
print("-----------------10-----------------")
KK_tea.total_sales()

-----------------1-----------------
Name: KK Regular Tea, Weight: 100
Tea Bags: 50, Price: 250
Status: None
-----------------2-----------------
Total sales: {'KK Regular Tea': 0}
-----------------3-----------------
-----------------4-----------------
Name: KK Regular Tea, Weight: 150
Tea Bags: 75, Price: 360
Status: True
-----------------5-----------------
Total sales: {'KK Regular Tea': 3}
-----------------6-----------------
-----------------7-----------------
Name: KK Jasmine Tea, Weight: 100
Tea Bags: 50, Price: 260
Status: None
-----------------8-----------------
Name: KK Honey Lemon Tea, Weight: 90
Tea Bags: 45, Price: 270
Status: None
-----------------9-----------------
-----------------10-----------------
Total sales: {'KK Regular Tea': 3, 'KK Jasmine Tea': 1, 'KK Honey Lemon Tea': 2}

In [ ]:
class Exam:
    def __init__(self,marks):
        self.marks = marks
        self.time = 60

    def examSyllabus(self):
        return "Maths , English"
    def examParts(self):
        return "Part 1 - Maths\nPart 2 - English\n"

class ScienceExam(Exam):
    def __init__(self,marks,time,*subj):
        super().__init__(marks)
        self.time=time
        self.subj=list(subj)
        self.parts=len(self.subj)+2
    def __str__(self):
        return f'Marks {self.marks} Time:{self.time}, Number of parts {self.parts}'

    def examSyllabus(self):
        x=super().examSyllabus()
        return f"{x} , {', '.join(self.subj)}"

    def examParts(self):
        x=super().examParts()
        for i in range (len(self.subj)):
            if i==0:
                x +=f'Part {i+3} - {self.subj[i]}'
            else:
                 x += f'\nPart {i+3} - {self.subj[i]}'
        return x

engineering = ScienceExam(100,90,"Physics","HigherMaths")
print(engineering)
print('----------------------------------')
print(engineering.examSyllabus())
print(engineering.examParts())
print('==================================')
architecture = ScienceExam(100,120,"Physics","HigherMaths","Drawing")
print(architecture)
print('----------------------------------')
print(architecture.examSyllabus())
print(architecture.examParts())

Marks 100 Time:90, Number of parts 4
----------------------------------
Maths , English , Physics, HigherMaths
Part 1 - Maths
Part 2 - English
Part 3 - Physics
Part 4 - HigherMaths
==================================
Marks 100 Time:120, Number of parts 5
----------------------------------
Maths , English , Physics, HigherMaths, Drawing
Part 1 - Maths
Part 2 - English
Part 3 - Physics
Part 4 - HigherMaths
Part 5 - Drawing

In [ ]:
class Cakes:
    order_list={}
    feedback={}
    def __init__(self,flavor,weight):
        self.flavor=flavor
        self.weight=weight
        self.sugar='Moderate Sugar'
        self.cream='Whipeed Cream'
        self.price=(self.weight*1.2)

        if self.flavor in Cakes.order_list:
            Cakes.order_list[f"{self.flavor} Cake {self.weight}gm"]+=1
        else:
            Cakes.order_list[f"{self.flavor} Cake {self.weight}gm"]=1

    def add_customization(self,sugar,cream):
        self.sugar=sugar
        self.cream=cream
    def cake_details(self):
        print(f"Flavor: {self.flavor} Cake, Weight: {self.weight} gm\nSweetness: {self.sugar}, Cream Type: {self.cream}\nPrice: {self.price} Taka")

    @classmethod
    def give_feedbacks(cls,cake,rev):
        print('Thank you for your valuable feedbacks')
        if cake in cls.feedback:
            cls.feedback[cake].append(rev)
        else:
            cls.feedback[cake]=[rev]

    @classmethod
    def show_feedbacks(self):
        print(Cakes.feedback)

class Cheese_Cakes(Cakes):
    def __init__(self,flavor,weight,types="baked"):
        super().__init__(flavor,weight)
        self.price=weight*1.5
        self.cream="Cream Cheese"
        self.sugar='Moderate Sugar'
        self.types=types

    def cake_details(self):
        print(f"Flavor: {self.flavor} Cake, Weight: {self.weight} gm\nSweetness: {self.sugar}, Cream Type: {self.cream}\nCake Type:{self.types}, Price: {self.price}")

    def add_customization(self):
        print("Sorry! No customization available for cheese cakes.")

    @classmethod
    def give_feedbacks(cls,cake,review):
        super().give_feedbacks(cake,review)
        print("You will get 10% discount for your next purchase!")

order_1=Cakes("Chocolate",500)
order_2=Cakes("Vanilla",800)
print("(1)**********************************")
order_1.cake_details()
print("(1.1)**********************************")
print(Cakes.order_list)
print("(2)**********************************")
order_2.add_customization("Zero","Butter Cream")
order_2.cake_details()
print("(3)**********************************")
Cakes.give_feedbacks("Chocolate Cake","Very Delicious")
Cakes.give_feedbacks("Chocolate Cake","Yummy")
print("(4)**********************************")
Cakes.show_feedbacks()
print("(5)**********************************")
ch_order1=Cheese_Cakes("Red velvet",700)
ch_order1.cake_details()
print("(6)**********************************")
ch_order1.add_customization()
print("(7)**********************************")
ch_order2=Cheese_Cakes("Blue Berry",900,"No Bake")
ch_order2.cake_details()
print("(8)**********************************")
print(Cakes.order_list)
print("(9)**********************************")
Cheese_Cakes.give_feedbacks("Red velvet Cheese Cake","Average")
Cheese_Cakes.give_feedbacks("Blue Berry Cheese Cake","Liked it")
print("(10)**********************************")
Cakes.show_feedbacks()

(1)**********************************
Flavor: Chocolate Cake, Weight: 500 gm
Sweetness: Moderate Sugar, Cream Type: Whipeed Cream
Price: 600.0 Taka
(1.1)**********************************
{'Chocolate Cake 500gm': 1, 'Vanilla Cake 800gm': 1}
(2)**********************************
Flavor: Vanilla Cake, Weight: 800 gm
Sweetness: Zero, Cream Type: Butter Cream
Price: 960.0 Taka
(3)**********************************
Thank you for your valuable feedbacks
Thank you for your valuable feedbacks
(4)**********************************
{'Chocolate Cake': ['Very Delicious', 'Yummy']}
(5)**********************************
Flavor: Red velvet Cake, Weight: 700 gm
Sweetness: Moderate Sugar, Cream Type: Cream Cheese
Cake Type:baked, Price: 1050.0
(6)**********************************
Sorry! No customization available for cheese cakes.
(7)**********************************
Flavor: Blue Berry Cake, Weight: 900 gm
Sweetness: Moderate Sugar, Cream Type: Cream Cheese
Cake Type:No Bake, Price: 1350.0
(8)**********************************
{'Chocolate Cake 500gm': 1, 'Vanilla Cake 800gm': 1, 'Red velvet Cake 700gm': 1, 'Blue Berry Cake 900gm': 1}
(9)**********************************
Thank you for your valuable feedbacks
You will get 10% discount for your next purchase!
Thank you for your valuable feedbacks
You will get 10% discount for your next purchase!
(10)**********************************
{'Chocolate Cake': ['Very Delicious', 'Yummy'], 'Red velvet Cheese Cake': ['Average'], 'Blue Berry Cheese Cake': ['Liked it']}

In [ ]:
class ChefsCounter:
    reservation={}

    def __init__(self,p,r=5):
        self.p=p
        self.r=r
        self.l=[]
        print(f"The {self.p} branch of Chef's Counter is open for reservation!")
    def reserve(self,*pep):
        for i in pep:
            if len(self.l)<self.r:
                self.l.append(i)
            else:
                print(f"Sorry {i} {self.r} people has already reserved this place")
                break
    def reservation_info(self):
       print(f"Customers who reserved is {self.p} branch is {','.join(self.l)}")
       ChefsCounter.reservation[self.p]=self.l
    @classmethod
    def createNewBranch(cls,p,r=5):
        obj=cls(p,r)
        return obj

print("===============1=============")
branch1 = ChefsCounter("Gulshan")
print("===============2=============")
branch1.reserve("Sam", "Paul")
print("===============3=============")
branch1.reservation_info()
print("===============4=============")
branch1.reserve("John", "Robin", "Billy",
"Robert")
print("===============5=============")
branch1.reservation_info()
print("===============6=============")
branch2 = ChefsCounter("Dhanmondi",7)
print("===============7=============")
branch2.reserve("Ben", "Alice", "Fred")
print("===============8=============")
branch2.reservation_info()
print("===============9=============")
branch2.reserve("Tom", "Ken", "Garet",
"Miles", "Taylor")
print("===============10=============")
branch2.reservation_info()
print("===============11=============")
branch3 = ChefsCounter.createNewBranch("100feet")
print("===============12=============")
branch3.reserve("Harry", "Bob", "Jenny")
print("===============13=============")
branch3.reservation_info()
print("===============14=============")
print("Reservation Information of AllBranches:",ChefsCounter.reservation)

===============1=============
The Gulshan branch of Chef's Counter is open for reservation!
===============2=============
===============3=============
Customers who reserved is Gulshan branch is Sam,Paul
===============4=============
Sorry Robert 5 people has already reserved this place
===============5=============
Customers who reserved is Gulshan branch is Sam,Paul,John,Robin,Billy
===============6=============
The Dhanmondi branch of Chef's Counter is open for reservation!
===============7=============
===============8=============
Customers who reserved is Dhanmondi branch is Ben,Alice,Fred
===============9=============
Sorry Taylor 7 people has already reserved this place
===============10=============
Customers who reserved is Dhanmondi branch is Ben,Alice,Fred,Tom,Ken,Garet,Miles
===============11=============
The 100feet branch of Chef's Counter is open for reservation!
===============12=============
===============13=============
Customers who reserved is 100feet branch is Harry,Bob,Jenny
===============14=============
Reservation Information of AllBranches: {'Gulshan': ['Sam', 'Paul', 'John', 'Robin', 'Billy'], 'Dhanmondi': ['Ben', 'Alice', 'Fred', 'Tom', 'Ken', 'Garet', 'Miles'], '100feet': ['Harry', 'Bob', 'Jenny']}

In [ ]:
class Ticket:
    route_distance = {"Route A":400, "Route B":425,"Route C":350}
    fare_per_km = 20
    def __init__(self, route, journeyDate, price = 0):
        self.route = route
        self.journeyDate = journeyDate
        self.__price = price
    def setPrice(self, price):
        self.__price = price
    def getPrice(self):
        return self.__price
    def ticket_details(self):
        return f"Route: {self.route}\nJourney Date:{self.journeyDate}"

class BusTicket(Ticket):
    total_tickets=0
    def __init__(self,route,journeyDate,name,seat):
        super().__init__(route,journeyDate,price=0)
        self.name=name
        self.seat=seat
        self.status=False
        BusTicket.total_tickets+=1
        self.id=self.name+'-'+str(BusTicket.total_tickets)
    def calculate_fare(self):
        if self.route in Ticket.route_distance:
            price= Ticket.route_distance[self.route]*Ticket.fare_per_km
            self.setPrice(price)
            print(f"Ticket Fare is calculated Succesfully")

    def make_payment(self):
        self.status=True

    def ticket_details(self):
        print(f"Ticket ID: {self.id}\nRoute:{self.route}\nJourney Date:{self.journeyDate}\nBus name: {self.name}\nSeat Num{self.seat}\nPrice Taka: {self.getPrice()}")
        if self.status==True:
            print(f"Paid")
        else:
            print(f"Not paid")


ticket1 = BusTicket("Route A", "30 April, 2023","Nabil Enterprise", "F2")
print("Total ticket(s):", BusTicket.total_tickets)
print("1============================")
ticket1.calculate_fare()
print("2============================")
ticket1.ticket_details()
print("3============================")
ticket1.make_payment()
print("4============================")
ticket1.ticket_details()
print("5============================")
ticket2 = BusTicket("Route C", "26 April, 2023","Hanif Enterprise", "A2")
print("Total ticket(s):", BusTicket.total_tickets)
print("6============================")
ticket2.calculate_fare()
print("7============================")
ticket2.make_payment()
print("8============================")
ticket2.ticket_details()

Total ticket(s): 1
1============================
Ticket Fare is calculated Succesfully
2============================
Ticket ID: Nabil Enterprise-1
Route:Route A
Journey Date:30 April, 2023
Bus name: Nabil Enterprise
Seat NumF2
Price Taka: 8000
Not paid
3============================
4============================
Ticket ID: Nabil Enterprise-1
Route:Route A
Journey Date:30 April, 2023
Bus name: Nabil Enterprise
Seat NumF2
Price Taka: 8000
Paid
5============================
Total ticket(s): 2
6============================
Ticket Fare is calculated Succesfully
7============================
8============================
Ticket ID: Hanif Enterprise-2
Route:Route C
Journey Date:26 April, 2023
Bus name: Hanif Enterprise
Seat NumA2
Price Taka: 7000
Paid

In [ ]:
class A:
    temp = 5
    def __init__(self):
        self.y = A.temp - 2
        self.sum = self.temp + 1
        A.temp += 3
        self.methodA(3, 6)
    def methodA(self, m, n):
        x = self.y + 4 + n
        self.sum = x + self.temp
        self.y = self.y + m + (A.temp)
        print(x, self.y, self.sum)
class B(A):
    def __init__(self, obj=None):
        super().__init__()
        self.temp = self.temp + A.temp
        self.sum = 5 + self.temp + A.temp
    def methodA(self, m, n, x=5):
        self.y = self.y + n + (A.temp)
        x = x + 3 + m
        self.sum = self.sum + x + self.temp
        print(x, self.y, self.sum)
    def methodB(self, m, n):
        y = self.temp + self.y + n
        A.temp = m + self.y + n
        super().methodA(n, m)
        self.methodA(n, m)
        self.sum = self.y + y + A.temp
        print(self.temp , y, self.sum)

b1 = B()
b1.methodB(5, 6)

11 17 25
26 51 42
14 84 72
16 39 151

In [ ]:
class Course:
    total_courses=0
    def __init__(self,id,name):
        self.id=id
        self.name=name
        Course.total_courses+=1

class Student:
    def __init__(self,name,id,cg,limit=None):
        self.name=name
        self.cg=cg
        self.id=id
        self.__limit=limit
        self.course=[]

    def setLimit(self):
        if self.cg<=2:
            self.__limit=2
        elif self.cg>3.50:
            self.__limit=5
        else:
            self.__limit=4
    def getLimit(self):
        return self.__limit

    def addCourses(self,*c):
        if self.__limit!=None:
            for i in c:
                self.course.append(i.id)
                print(f"{i.id} is added to the course list")
        else:
            print(f"Sorry total Course limit is not set")

    def printDetails(self):
        print(f'Student Id:{self.id}\nStudent Name : {self.name}')
        print(f'Courses Taken : {",".join(self.course)}')
print(f"Number of courses:{Course.total_courses}")
print("1--------------------------")
c1 = Course("CSE220", "Data Structures")
c2 = Course("CSE230", "Discrete Mathematics")
c3 = Course("CSE250", "Circuits and Electronics")
c4 = Course("MAT120", "Mathematics II")
c5 = Course("PHY112", "Principles of Physics II")
c6 = Course("STA201", "Statistics I")
c7 = Course("ENG102", "English Composition")
print("2--------------------------")
print(f"Number of courses:{Course.total_courses}")
print("3--------------------------")
s1 = Student("Alice",3242544,2.39)
s2 = Student("Bob",9878686,3.92)
s3 = Student("Carol",2346678,1.67)
print("4--------------------------")
s1.addCourses(c1,c2)
print("5--------------------------")
s1.setLimit()
print("6--------------------------")
print(f"Course limit of {s1.name}is:{s1.getLimit()}")
s1.addCourses(c4,c5,c7)
print("7--------------------------")
s1.addCourses(c1,c2)
print("8--------------------------")
s1.printDetails()
print("9--------------------------")
s2.setLimit()
s3.setLimit()
print("10--------------------------")
print(f"Course limit of {s2.name}is:{s2.getLimit()}")
print(f"Course limit of {s3.name}is:{s3.getLimit()}")
print("11--------------------------")
s2.addCourses(c1,c2,c4,c5,c7)
print("12--------------------------")
s3.addCourses(c2,c4,c5,c7)
print("13--------------------------")
s1.printDetails()
print("14--------------------------")
s2.printDetails()
print("15--------------------------")
s3.printDetails()

Number of courses:0
1--------------------------
2--------------------------
Number of courses:7
3--------------------------
4--------------------------
Sorry total Course limit is not set
5--------------------------
6--------------------------
Course limit of Aliceis:4
MAT120 is added to the course list
PHY112 is added to the course list
ENG102 is added to the course list
7--------------------------
CSE220 is added to the course list
CSE230 is added to the course list
8--------------------------
Student Id:3242544
Student Name : Alice
Courses Taken : MAT120,PHY112,ENG102,CSE220,CSE230
9--------------------------
10--------------------------
Course limit of Bobis:5
Course limit of Carolis:2
11--------------------------
CSE220 is added to the course list
CSE230 is added to the course list
MAT120 is added to the course list
PHY112 is added to the course list
ENG102 is added to the course list
12--------------------------
CSE230 is added to the course list
MAT120 is added to the course list
PHY112 is added to the course list
ENG102 is added to the course list
13--------------------------
Student Id:3242544
Student Name : Alice
Courses Taken : MAT120,PHY112,ENG102,CSE220,CSE230
14--------------------------
Student Id:9878686
Student Name : Bob
Courses Taken : CSE220,CSE230,MAT120,PHY112,ENG102
15--------------------------
Student Id:2346678
Student Name : Carol
Courses Taken : CSE230,MAT120,PHY112,ENG102

In [ ]:
class Workspace:
    def __init__(self, workspaceName, type):
        self.workspaceName = workspaceName
        self.type = type
        self.channels = {}
    def checkChannelExistence(self, channelName):
        if channelName in self.channels:
            return True
            return False
    def __str__(self):
        return f"Name: {self.workspaceName}\nType:{self.type}\n"

class  SlackWorkspace(Workspace):
    total_workspaces=0
    def __init__(self,workspaceName,type,sections=3):
        super().__init__(workspaceName,type)
        self.sections=sections
        print(f"CSE111Workspace is created.")
        SlackWorkspace.total_workspaces+=1
        self.channels={}
        self.total_members=0

    def createChannels(self):
        for i in range(1,self.sections+1):
            self.channels[f"Section-{str(i)}"]=[]

    def addMembersToChannel(self,*mem):
        for i in mem:
            name,num=i.split('_')
            x=f"Section-{str(num)}"
            if x in self.channels:
                self.channels[x]=[name]
                self.total_members+=1
            else:
                print(f"Sorry {name} section-{num} channel not found in {self.workspaceName}")

    def __str__(self):
        x=super().__str__()
        return f"{x}Total Members {self.total_members}\nTotal Channels {len(self.channels)}\nChannel Info : {self.channels}"

print(f"Total no. of workspaces:{SlackWorkspace.total_workspaces}")
print("1=============================")
CSE111Workspace = SlackWorkspace("CSE111Workspace",
"Education",5)
print("2=============================")
print(CSE111Workspace)
print(f"Total no. of workspaces:{SlackWorkspace.total_workspaces}")
print("3=============================")
CSE111Workspace.createChannels()
print("4=============================")
print(CSE111Workspace)
print("5=============================")
john, harry, adil = "John_2", "Harry_10", "Adil_1"
alice, bob = "Alice_2","Bob_3"
print("6=============================")
CSE111Workspace.addMembersToChannel(john, harry)
CSE111Workspace.addMembersToChannel(adil)
print("7=============================")
del(CSE111Workspace.channels["Section-3"])
print(CSE111Workspace)
print("8=============================")
CSE111Workspace.addMembersToChannel(alice, bob)
print("9=============================")
print(CSE111Workspace)
print("10=============================")
CSE320Workspace = SlackWorkspace("CSE320Workspace","Education")
CSE320Workspace.createChannels()
print("11=============================")
print(CSE320Workspace)
print("12=============================")
print(f"Total no. of workspaces:{SlackWorkspace.total_workspaces}")

Total no. of workspaces:0
1=============================
CSE111Workspace is created.
2=============================
Name: CSE111Workspace
Type:Education
Total Members 0
Total Channels 0
Channel Info : {}
Total no. of workspaces:1
3=============================
4=============================
Name: CSE111Workspace
Type:Education
Total Members 0
Total Channels 5
Channel Info : {'Section-1': [], 'Section-2': [], 'Section-3': [], 'Section-4': [], 'Section-5': []}
5=============================
6=============================
Sorry Harry section-10 channel not found in CSE111Workspace
7=============================
Name: CSE111Workspace
Type:Education
Total Members 2
Total Channels 4
Channel Info : {'Section-1': ['Adil'], 'Section-2': ['John'], 'Section-4': [], 'Section-5': []}
8=============================
Sorry Bob section-3 channel not found in CSE111Workspace
9=============================
Name: CSE111Workspace
Type:Education
Total Members 3
Total Channels 4
Channel Info : {'Section-1': ['Adil'], 'Section-2': ['Alice'], 'Section-4': [], 'Section-5': []}
10=============================
CSE111Workspace is created.
11=============================
Name: CSE320Workspace
Type:Education
Total Members 0
Total Channels 3
Channel Info : {'Section-1': [], 'Section-2': [], 'Section-3': []}
12=============================
Total no. of workspaces:2

In [ ]:
class A:
    temp = 3

    def __init__(self):
        temp = 5
        self.y = 6
        self.sum = self.temp + 1
        self.temp += 2
        A.temp += 4

    def methodA(self, m, n):
        x = self.temp + 4 + n
        self.sum = x + self.temp
        self.y = self.y + m + (A.temp)
        print(x, self.y, self.sum)

class B(A):
    def __init__(self):
        super().__init__()
        self.temp = self.temp + A.temp
        self.sum = 5 + self.temp + A.temp

    def methodA(self, m, n):
        x = A.temp + 3 + n
        self.sum = self.sum + x + self.temp
        self.y = A.temp - self.y - n
        print(x, self.y, self.sum)

    def methodB(self, b):
        n = self.temp + b.temp
        B.temp = self.sum + self.y + n
        b.methodA(n, B.temp)
        self.methodA(B.temp, n)

a1 = A()
b1 = B()
b1.methodB(a1)
b1.methodA(-2, 1)

76 42 81
39 -20 95
15 30 130

In [ ]:
class Mobile:
    countryCodes = {"880": "Bangladesh", "966": "India",
    "455": "USA"}
    def __init__(self, model, simCardStatus):
        self.model = model
        self.__simCardStatus = simCardStatus
        print(f"Model {model} is manufactured.")
    def setSimCardStatus(self,status):
        self.__simCardStatus = status
        print("SIM card status updated successfully.")
    def getSimCardStatus(self):
        return self.__simCardStatus
    def __str__(self):

        return f"Mobile Phone Detail:\nModel:{self.model}\nSIM Card Status: {self.__simCardStatus}"

class Nokia(Mobile):
    def __init__(self,model, simCardStatus,balance=0):
        super().__init__(model, simCardStatus)
        self.balance=balance
        self.dialCallHistory=[]
    def changeSIMCardStatus(self):
        self.setSimCardStatus(True)
    def rechargeSIMCard(self,amount):
        self.balance+=amount
        print(f'Recharge Successfull Current Balance {self.balance}')
    def dialCall(self,num):
        if self.getSimCardStatus()==True:
            if self.balance>0:
                if num[:3] in Mobile.countryCodes:
                    x=(f"Dialing the number {num} to  {Mobile.countryCodes[num[:3]]} ")
                    self.dialCallHistory.append(num)
                else:
                    x=(f"Dialing is not allowed in this region")
            else:
                x=(f"Insufficient Balance")

        else:
            x=('No Sim card available')
        return x

N3110 = Nokia("N3110", False)
print("#######################################")
print(N3110)
print("1======================================")
N1100 = Nokia("N1100", True,100)
print("#######################################")
print(N1100)
print("2======================================")
print(N3110.dialCall("88017196xxxx"))
print("3======================================")
N3110.changeSIMCardStatus()
print("4======================================")
print(N3110.dialCall("88017196xxxx"))
print("5======================================")
N3110.rechargeSIMCard(200)
print("6======================================")
print(N3110.dialCall("88017196xxxx"))
print("7======================================")
print(N1100.dialCall("45617196xxxx"))
print("8======================================")
print(N1100.dialCall("45517196xxxx"))
print(N1100.dialCall("96617196xxxx"))
print("9======================================")
print(f"Dial call history for {N1100.model}:{N1100.dialCallHistory}")

print(f"Dial call history for {N3110.model}:{N3110.dialCallHistory}")

Model N3110 is manufactured.
#######################################
Mobile Phone Detail:
Model:N3110
SIM Card Status: False
1======================================
Model N1100 is manufactured.
#######################################
Mobile Phone Detail:
Model:N1100
SIM Card Status: True
2======================================
No Sim card available
3======================================
SIM card status updated successfully.
4======================================
Insufficient Balance
5======================================
Recharge Successfull Current Balance 200
6======================================
Dialing the number 88017196xxxx to  Bangladesh
7======================================
Dialing is not allowed in this region
8======================================
Dialing the number 45517196xxxx to  USA
Dialing the number 96617196xxxx to  India
9======================================
Dial call history for N1100:['45517196xxxx', '96617196xxxx']
Dial call history for N3110:['88017196xxxx']

In [ ]:
class User:
    activities = ["Post", "Like", "Comment"]
    def __init__(self, name,email):
        self.name = name
        self.email = email
    def UserActivity(self, activityType):
        if activityType in User.activities:
            return True
        else:
            return False
    def userDetail(self):
        return f"User Detail:\nName:{self.name}\nEmail: {self.email}"
class BracbookUser(User):
    def __init__(self,name,email,phone='Not set'):
        super().__init__(name,email)
        self.phone=phone
        self.activity_log=[]
    def userDetail(self):
        x = f"User Detail:\nName:{self.name}\nEmail: {self.email}\nPhone : {self.phone}\n"
        if len(self.activity_log)==0:
            x+=f"Activity Log: No recent activity"
        else:
            x+=f"Activity log: {','.join(self.activity_log)}"
        return x
    def UserActivity(self,act):
        x=super().UserActivity(act)
        if x==True:
            self.activity_log.append(act)
            print(f"{self.name} has {act} successfully")
        else:
            print('No activities found like this')

user1 = BracbookUser("Rakait","xyz@gmail.com")
print("1===========================")
print(user1.userDetail())
print("2===========================")
user2 = BracbookUser("Sazzad","abc@gmail.com",
"01727xxxxxx")
print("3===========================")
print(user2.userDetail())
print("4===========================")
user1.UserActivity("Like")
print("5===========================")
user1.UserActivity("Comment")
print("6===========================")
print(user1.userDetail())
print("7===========================")
user2.UserActivity("Share")
print("8===========================")
user2.UserActivity("Comment")
print("9===========================")
print(user2.userDetail())

1===========================
User Detail:
Name:Rakait
Email: xyz@gmail.com
Phone : Not set
Activity Log: No recent activity
2===========================
3===========================
User Detail:
Name:Sazzad
Email: abc@gmail.com
Phone : 01727xxxxxx
Activity Log: No recent activity
4===========================
Rakait has Like successfully
5===========================
Rakait has Comment successfully
6===========================
User Detail:
Name:Rakait
Email: xyz@gmail.com
Phone : Not set
Activity log: Like,Comment
7===========================
No activities found like this
8===========================
Sazzad has Comment successfully
9===========================
User Detail:
Name:Sazzad
Email: abc@gmail.com
Phone : 01727xxxxxx
Activity log: Comment

In [ ]:
class A:
    temp = 7

    def __init__(self):
        self.y = A.temp - 3
        self.sum = self.temp + 2
        A.temp += 3

    def methodA(self, m, n, x=0):
        self.y = self.y + m + (A.temp)
        x = x + 2 + n
        self.sum = self.sum + x + self.temp
        print(x, self.y, self.sum)

class B(A):
    temp = 1

    def __init__(self, obj=None):
        super().__init__()
        self.temp = self.temp + B.temp
        self.sum = 3 + B.temp + A.temp
        if obj is not None:
            obj.methodB(3, 6)
        else:
            self.methodB(1, 4)

    def methodB(self, m, n):
        y = self.temp + self.y + n
        B.temp = m + self.y + n
        self.methodA(n, m)
        self.sum = self.y + y + A.temp
        print(self.temp, y, self.sum)

b1 = B()
b2 = B(b1)

3 18 19
2 10 38
5 37 45
2 26 76